export interface AntonymPair {
    word1: string;
    word2: string;
}

export const antonymsData: AntonymPair[] = [
    { word1: "groß", word2: "klein" },
    { word1: "gut", word2: "schlecht" },
    { word1: "hell", word2: "dunkel" },
    { word1: "kalt", word2: "warm" },
    { word1: "laut", word2: "leise" },
    { word1: "neu", word2: "alt" },
    { word1: "schnell", word2: "langsam" },
    { word1: "schwer", word2: "leicht" },
    { word1: "stark", word2: "schwach" },
    { word1: "süß", word2: "sauer" },
    { word1: "voll", word2: "leer" },
    { word1: "weiß", word2: "schwarz" },
    { word1: "jung", word2: "alt" },
    { word1: "dick", word2: "dünn" },
    { word1: "hoch", word2: "tief" },
    { word1: "breit", word2: "schmal" },
    { word1: "vorn", word2: "hinten" },
    { word1: "oben", word2: "unten" },
    { word1: "drinnen", word2: "draußen" },
    { word1: "offen", word2: "zu" },
    { word1: "sauber", word2: "dreckig" },
    { word1: "lustig", word2: "traurig" },
    { word1: "teuer", word2: "billig" },
    { word1: "schön", word2: "hässlich" },
    { word1: "hart", word2: "weich" },
    { word1: "lang", word2: "kurz" },
    { word1: "früh", word2: "spät" },
    { word1: "richtig", word2: "falsch" },
    { word1: "fleißig", word2: "faul" },
    { word1: "klug", word2: "dumm" },
    { word1: "reich", word2: "arm" },
    { word1: "gesund", word2: "krank" },
    { word1: "trocken", word2: "nass" },
    { word1: "rund", word2: "eckig" },
    { word1: "glatt", word2: "rau" },
    { word1: "mutig", word2: "ängstlich" },
    { word1: "sicher", word2: "gefährlich" },
    { word1: "liebevoll", word2: "böse" },
    { word1: "ruhig", word2: "unruhig" },
    { word1: "wichtig", word2: "unwichtig" },
    { word1: "erlaubt", word2: "verboten" },
    { word1: "müde", word2: "wach" },
    { word1: "hungrig", word2: "satt" },
    { word1: "nah", word2: "fern" },
    { word1: "einfach", word2: "schwer" },
    { word1: "freundlich", word2: "unfreundlich" },
    { word1: "geduldig", word2: "ungeduldig" },
    { word1: "glücklich", word2: "unglücklich" },
    { word1: "interessant", word2: "langweilig" },
    { word1: "wahr", word2: "gelogen" }
];
