import type { NounItem } from './artikelData';

export interface RhymeItem {
    word: string;
    rhyme: string;
    distractors: string[];
    emoji: string;
}

export interface GapItem {
    sentence: string[];
    answer: string;
    options: string[];
    emoji: string;
}

export interface SyllableItem {
    word: string;
    syllables: string[];
    emoji: string;
}

export interface WordMatchItem {
    word: string;
    options: string[];
    emoji: string;
}

export interface UnscrambleItem {
    word: string;
    emoji: string;
}

export interface FishingItem {
    target: string;
    pool: string[];
    emoji: string;
}

export const expandedArtikelData: NounItem[] = [
    { word: 'Apfel', gender: 'der', emoji: '🍎' },
    { word: 'Banane', gender: 'die', emoji: '🍌' },
    { word: 'Auto', gender: 'das', emoji: '🚗' },
    { word: 'Baum', gender: 'der', emoji: '🌳' },
    { word: 'Blume', gender: 'die', emoji: '🌸' },
    { word: 'Buch', gender: 'das', emoji: '📖' },
    { word: 'Hund', gender: 'der', emoji: '🐕' },
    { word: 'Katze', gender: 'die', emoji: '🐈' },
    { word: 'Haus', gender: 'das', emoji: '🏠' },
    { word: 'Tisch', gender: 'der', emoji: '🪑' },
    { word: 'Sonne', gender: 'die', emoji: '☀️' },
    { word: 'Kind', gender: 'das', emoji: '👶' },
    { word: 'Vogel', gender: 'der', emoji: '🐦' },
    { word: 'Maus', gender: 'die', emoji: '🐭' },
    { word: 'Brot', gender: 'das', emoji: '🍞' },
    { word: 'Löffel', gender: 'der', emoji: '🥄' },
    { word: 'Gabel', gender: 'die', emoji: '🍴' },
    { word: 'Messer', gender: 'das', emoji: '🔪' },
    { word: 'Stuhl', gender: 'der', emoji: '🪑' },
    { word: 'Tante', gender: 'die', emoji: '👩' },
    { word: 'Fahrrad', gender: 'das', emoji: '🚲' },
    { word: 'Berg', gender: 'der', emoji: '⛰️' },
    { word: 'Wolke', gender: 'die', emoji: '☁️' },
    { word: 'Wasser', gender: 'das', emoji: '💧' },
    { word: 'Schlüssel', gender: 'der', emoji: '🔑' },
    { word: 'Tasche', gender: 'die', emoji: '👜' },
    { word: 'Handy', gender: 'das', emoji: '📱' },
    { word: 'Ball', gender: 'der', emoji: '⚽' },
    { word: 'Puppe', gender: 'die', emoji: '🪆' },
    { word: 'Spiel', gender: 'das', emoji: '🎮' },
    { word: 'Kuchen', gender: 'der', emoji: '🍰' },
    { word: 'Milch', gender: 'die', emoji: '🥛' },
    { word: 'Eis', gender: 'das', emoji: '🍦' },
    { word: 'Zug', gender: 'der', emoji: '🚂' },
    { word: 'Uhr', gender: 'die', emoji: '⌚' },
    { word: 'Schiff', gender: 'das', emoji: '🚢' },
    { word: 'Aprikose', gender: 'die', emoji: '🍑' }, // Some more complex ones
    { word: 'Elefant', gender: 'der', emoji: '🐘' },
    { word: 'Giraffe', gender: 'die', emoji: '🦒' },
    { word: 'Krokodil', gender: 'das', emoji: '🐊' },
    { word: 'Löwe', gender: 'der', emoji: '🦁' },
    { word: 'Schlange', gender: 'die', emoji: '🐍' },
    { word: 'Pony', gender: 'das', emoji: '🐴' },
    { word: 'Wald', gender: 'der', emoji: '🌲' },
    { word: 'Wiese', gender: 'die', emoji: '🌱' },
    { word: 'Heft', gender: 'das', emoji: '📒' },
    { word: 'Bleistift', gender: 'der', emoji: '✏️' },
    { word: 'Schere', gender: 'die', emoji: '✂️' },
    { word: 'Lineal', gender: 'das', emoji: '📏' },
    { word: 'Regenschirm', gender: 'der', emoji: '☂️' },
    { word: 'Jacke', gender: 'die', emoji: '🧥' },
    { word: 'T-Shirt', gender: 'das', emoji: '👕' },
    { word: 'Schuh', gender: 'der', emoji: '👞' },
    { word: 'Hose', gender: 'die', emoji: '👖' },
    { word: 'Kleid', gender: 'das', emoji: '👗' },
    { word: 'Hut', gender: 'der', emoji: '🎩' },
    { word: 'Brille', gender: 'die', emoji: '👓' },
    { word: 'Auge', gender: 'das', emoji: '👁️' },
    { word: 'Mund', gender: 'der', emoji: '👄' },
    { word: 'Nase', gender: 'die', emoji: '👃' },
    { word: 'Ohr', gender: 'das', emoji: '👂' },
    { word: 'Finger', gender: 'der', emoji: '☝️' },
    { word: 'Hand', gender: 'die', emoji: '✋' },
    { word: 'Bein', gender: 'das', emoji: '🦵' },
    { word: 'Kopf', gender: 'der', emoji: '👤' },
    { word: 'Schulter', gender: 'die', emoji: '💪' },
    { word: 'Herz', gender: 'das', emoji: '❤️' },
    { word: 'Tag', gender: 'der', emoji: '🌅' },
    { word: 'Nacht', gender: 'die', emoji: '🌃' },
    { word: 'Jahr', gender: 'das', emoji: '📅' },
    { word: 'Mond', gender: 'der', emoji: '🌙' },
    { word: 'Stern', gender: 'der', emoji: '⭐' },
    { word: 'Erde', gender: 'die', emoji: '🌍' },
    { word: 'Feuer', gender: 'das', emoji: '🔥' },
    { word: 'Wind', gender: 'der', emoji: '💨' },
    { word: 'Luft', gender: 'die', emoji: '🌬️' },
    { word: 'Licht', gender: 'das', emoji: '💡' },
    { word: 'Schatten', gender: 'der', emoji: '🌑' },
    { word: 'Spiegel', gender: 'der', emoji: '🪞' },
    { word: 'Tür', gender: 'die', emoji: '🚪' },
    { word: 'Fenster', gender: 'das', emoji: '🪟' },
    { word: 'Dach', gender: 'das', emoji: '🏠' },
    { word: 'Garten', gender: 'der', emoji: '🏡' },
    { word: 'Zaun', gender: 'der', emoji: '🚧' },
    { word: 'Weg', gender: 'der', emoji: '🛤️' },
    { word: 'Straße', gender: 'die', emoji: '🛣️' },
    { word: 'Stadt', gender: 'die', emoji: '🏙️' },
    { word: 'Dorf', gender: 'das', emoji: '🏘️' },
    { word: 'Land', gender: 'das', emoji: '🗺️' },
    { word: 'Fluss', gender: 'der', emoji: '🌊' },
    { word: 'See', gender: 'der', emoji: '🏞️' },
    { word: 'Meer', gender: 'das', emoji: '🌊' },
    { word: 'Insel', gender: 'die', emoji: '🏝️' },
    { word: 'Himmel', gender: 'der', emoji: '🌌' },
    { word: 'Regen', gender: 'der', emoji: '🌧️' },
    { word: 'Schnee', gender: 'der', emoji: '❄️' },
    { word: 'Eisbär', gender: 'der', emoji: '🐻‍❄️' },
    { word: 'Pinguin', gender: 'der', emoji: '🐧' },
    { word: 'Zebra', gender: 'das', emoji: '🦓' },
    { word: 'Känguru', gender: 'das', emoji: '🦘' },
    { word: 'Affe', gender: 'der', emoji: '🐒' },
    { word: 'Tiger', gender: 'der', emoji: '🐅' },
    { word: 'Bär', gender: 'der', emoji: '🐻' },
    { word: 'Wolf', gender: 'der', emoji: '🐺' },
    { word: 'Fuchs', gender: 'der', emoji: '🦊' },
    { word: 'Hase', gender: 'der', emoji: '🐰' },
    { word: 'Igel', gender: 'der', emoji: '🦔' },
    { word: 'Eichhörnchen', gender: 'das', emoji: '🐿️' },
    { word: 'Reh', gender: 'das', emoji: '🦌' },
    { word: 'Schwein', gender: 'das', emoji: '🐷' },
    { word: 'Kuh', gender: 'die', emoji: '🐮' },
    { word: 'Schaf', gender: 'das', emoji: '🐑' },
    { word: 'Ziege', gender: 'die', emoji: '🐐' },
    { word: 'Huhn', gender: 'das', emoji: '🐔' },
    { word: 'Ente', gender: 'die', emoji: '🦆' },
    { word: 'Gans', gender: 'die', emoji: '🪿' },
    { word: 'Biene', gender: 'die', emoji: '🐝' },
    { word: 'Käfer', gender: 'der', emoji: '🐞' },
    { word: 'Spinne', gender: 'die', emoji: '🕷️' },
    { word: 'Fisch', gender: 'der', emoji: '🐟' },
    { word: 'Haifisch', gender: 'der', emoji: '🦈' },
    { word: 'Wal', gender: 'der', emoji: '🐋' },
    { word: 'Krabbe', gender: 'die', emoji: '🦀' },
    { word: 'Schildkröte', gender: 'die', emoji: '🐢' }
];

export const expandedSyllableData: SyllableItem[] = [
    { word: 'Apfel', syllables: ['Ap', 'fel'], emoji: '🍎' },
    { word: 'Banane', syllables: ['Ba', 'na', 'ne'], emoji: '🍌' },
    { word: 'Zitrone', syllables: ['Zi', 'tro', 'ne'], emoji: '🍋' },
    { word: 'Ananas', syllables: ['A', 'na', 'nas'], emoji: '🍍' },
    { word: 'Erdbeere', syllables: ['Erd', 'bee', 're'], emoji: '🍓' },
    { word: 'Kirsche', syllables: ['Kir', 'sche'], emoji: '🍒' },
    { word: 'Traube', syllables: ['Trau', 'be'], emoji: '🍇' },
    { word: 'Birne', syllables: ['Bir', 'ne'], emoji: '🍐' },
    { word: 'Melone', syllables: ['Me', 'lo', 'ne'], emoji: '🍉' },
    { word: 'Mango', syllables: ['Man', 'go'], emoji: '🥭' },
    { word: 'Tomate', syllables: ['To', 'ma', 'te'], emoji: '🍅' },
    { word: 'Kartoffel', syllables: ['Kar', 'tof', 'fel'], emoji: '🥔' },
    { word: 'Paprika', syllables: ['Pa', 'pri', 'ka'], emoji: '🫑' },
    { word: 'Gurke', syllables: ['Gur', 'ke'], emoji: '🥒' },
    { word: 'Zucchini', syllables: ['Zuc', 'chi', 'ni'], emoji: '🥒' },
    { word: 'Karotte', syllables: ['Ka', 'rot', 'te'], emoji: '🥕' },
    { word: 'Zwiebel', syllables: ['Zwie', 'bel'], emoji: '🧅' },
    { word: 'Knoblauch', syllables: ['Knob', 'lauch'], emoji: '🧄' },
    { word: 'Brokkoli', syllables: ['Brok', 'ko', 'li'], emoji: '🥦' },
    { word: 'Spinat', syllables: ['Spi', 'nat'], emoji: '🥬' },
    { word: 'Salat', syllables: ['Sa', 'lat'], emoji: '🥗' },
    { word: 'Bohne', syllables: ['Boh', 'ne'], emoji: '🫘' },
    { word: 'Erbse', syllables: ['Erb', 'se'], emoji: '🫛' },
    { word: 'Mais', syllables: ['Mais'], emoji: '🌽' },
    { word: 'Reis', syllables: ['Reis'], emoji: '🍚' },
    { word: 'Nudel', syllables: ['Nu', 'del'], emoji: '🍝' },
    { word: 'Pizza', syllables: ['Piz', 'za'], emoji: '🍕' },
    { word: 'Burger', syllables: ['Bur', 'ger'], emoji: '🍔' },
    { word: 'Pommes', syllables: ['Pom', 'mes'], emoji: '🍟' },
    { word: 'Wurst', syllables: ['Wurst'], emoji: '🌭' },
    { word: 'Käse', syllables: ['Kä', 'se'], emoji: '🧀' },
    { word: 'Butter', syllables: ['But', 'ter'], emoji: '🧈' },
    { word: 'Milch', syllables: ['Milch'], emoji: '🥛' },
    { word: 'Joghurt', syllables: ['Jo', 'ghurt'], emoji: '🍦' },
    { word: 'Honig', syllables: ['Ho', 'nig'], emoji: '🍯' },
    { word: 'Kekse', syllables: ['Kek', 'se'], emoji: '🍪' },
    { word: 'Schokolade', syllables: ['Scho', 'ko', 'la', 'de'], emoji: '🍫' },
    { word: 'Bonbon', syllables: ['Bon', 'bon'], emoji: '🍬' },
    { word: 'Lollipop', syllables: ['Lol', 'li', 'pop'], emoji: '🍭' },
    { word: 'Kuchen', syllables: ['Ku', 'chen'], emoji: '🍰' },
    { word: 'Torte', syllables: ['Tor', 'te'], emoji: '🎂' },
    { word: 'Eiscreme', syllables: ['Eis', 'cre', 'me'], emoji: '🍦' },
    { word: 'Sonne', syllables: ['Son', 'ne'], emoji: '☀️' },
    { word: 'Regen', syllables: ['Re', 'gen'], emoji: '🌧️' },
    { word: 'Wolke', syllables: ['Wol', 'ke'], emoji: '☁️' },
    { word: 'Schnee', syllables: ['Schnee'], emoji: '❄️' },
    { word: 'Donner', syllables: ['Don', 'ner'], emoji: '⚡' },
    { word: 'Blitz', syllables: ['Blitz'], emoji: '🌩️' },
    { word: 'Himmel', syllables: ['Him', 'mel'], emoji: '🌌' },
    { word: 'Sterne', syllables: ['Ster', 'ne'], emoji: '⭐' },
    { word: 'Mond', syllables: ['Mond'], emoji: '🌙' },
    { word: 'Erde', syllables: ['Er', 'de'], emoji: '🌍' },
    { word: 'Mars', syllables: ['Mars'], emoji: '🔴' },
    { word: 'Venus', syllables: ['Ve', 'nus'], emoji: '🪐' },
    { word: 'Rakete', syllables: ['Ra', 'ke', 'te'], emoji: '🚀' },
    { word: 'Ufo', syllables: ['U', 'fo'], emoji: '🛸' },
    { word: 'Auto', syllables: ['Au', 'to'], emoji: '🚗' },
    { word: 'Lkw', syllables: ['Lkw'], emoji: '🚛' },
    { word: 'Bus', syllables: ['Bus'], emoji: '🚌' },
    { word: 'Taxi', syllables: ['Ta', 'xi'], emoji: '🚕' },
    { word: 'Fahrrad', syllables: ['Fahr', 'rad'], emoji: '🚲' },
    { word: 'Motorrad', syllables: ['Mo', 'tor', 'rad'], emoji: '🏍️' },
    { word: 'Roller', syllables: ['Rol', 'ler'], emoji: '🛴' },
    { word: 'Traktor', syllables: ['Trak', 'tor'], emoji: '🚜' },
    { word: 'Bagger', syllables: ['Bag', 'ger'], emoji: '🏗️' },
    { word: 'Kran', syllables: ['Kran'], emoji: '🏗️' },
    { word: 'Zug', syllables: ['Zug'], emoji: '🚂' },
    { word: 'U-Bahn', syllables: ['U-Bahn'], emoji: '🚇' },
    { word: 'Flugzeug', syllables: ['Flug', 'zeug'], emoji: '✈️' },
    { word: 'Hubschrauber', syllables: ['Hub', 'schrau', 'ber'], emoji: '🚁' },
    { word: 'Schiff', syllables: ['Schiff'], emoji: '🚢' },
    { word: 'Boot', syllables: ['Boot'], emoji: '🛥️' },
    { word: 'Kanu', syllables: ['Ka', 'nu'], emoji: '🛶' },
    { word: 'Segelboot', syllables: ['Se', 'gel', 'boot'], emoji: '⛵' },
    { word: 'Anker', syllables: ['An', 'ker'], emoji: '⚓' },
    { word: 'Leuchtturm', syllables: ['Leucht', 'turm'], emoji: '🗼' },
    { word: 'Insel', syllables: ['In', 'sel'], emoji: '🏝️' },
    { word: 'Strand', syllables: ['Strand'], emoji: '🏖️' },
    { word: 'Muschel', syllables: ['Mu', 'schel'], emoji: '🐚' },
    { word: 'Palme', syllables: ['Pal', 'me'], emoji: '🌴' },
    { word: 'Dschungel', syllables: ['Dschun', 'gel'], emoji: '🌳' },
    { word: 'Berg', syllables: ['Berg'], emoji: '⛰️' },
    { word: 'Tal', syllables: ['Tal'], emoji: '🏞️' },
    { word: 'Wald', syllables: ['Wald'], emoji: '🌲' },
    { word: 'Fluss', syllables: ['Fluss'], emoji: '🌊' },
    { word: 'Wasserfall', syllables: ['Was', 'ser', 'fall'], emoji: '⛲' },
    { word: 'Wüste', syllables: ['Wüs', 'te'], emoji: '🏜️' },
    { word: 'Vulkan', syllables: ['Vul', 'kan'], emoji: '🌋' },
    { word: 'Haus', syllables: ['Haus'], emoji: '🏠' },
    { word: 'Wohnung', syllables: ['Woh', 'nung'], emoji: '🏢' },
    { word: 'Zimmer', syllables: ['Zim', 'mer'], emoji: '🛌' },
    { word: 'Küche', syllables: ['Kü', 'che'], emoji: '🍳' },
    { word: 'Bad', syllables: ['Bad'], emoji: '🛀' },
    { word: 'Balkon', syllables: ['Bal', 'kon'], emoji: '🪵' },
    { word: 'Garten', syllables: ['Gar', 'ten'], emoji: '🏡' },
    { word: 'Fenster', syllables: ['Fen', 'ster'], emoji: '🪟' },
    { word: 'Tür', syllables: ['Tür'], emoji: '🚪' },
    { word: 'Treppe', syllables: ['Trep', 'pe'], emoji: '🪜' },
    { word: 'Dach', syllables: ['Dach'], emoji: '🏠' },
    { word: 'Keller', syllables: ['Kel', 'ler'], emoji: '📦' },
    { word: 'Schlüssel', syllables: ['Schlüs', 'sel'], emoji: '🔑' },
    { word: 'Schloss', syllables: ['Schloss'], emoji: '🔒' },
    { word: 'Koffer', syllables: ['Kof', 'fer'], emoji: '🧳' },
    { word: 'Tasche', syllables: ['Ta', 'sche'], emoji: '👜' },
    { word: 'Geld', syllables: ['Geld'], emoji: '💰' },
    { word: 'Karte', syllables: ['Kar', 'te'], emoji: '🃏' },
    { word: 'Würfel', syllables: ['Wür', 'fel'], emoji: '🎲' },
    { word: 'Puppe', syllables: ['Pup', 'pe'], emoji: '🪆' },
    { word: 'Teddy', syllables: ['Ted', 'dy'], emoji: '🧸' },
    { word: 'Ball', syllables: ['Ball'], emoji: '⚽' },
    { word: 'Fahrrad', syllables: ['Fahr', 'rad'], emoji: '🚲' },
    { word: 'Skateboard', syllables: ['Skate', 'board'], emoji: '🛹' },
    { word: 'Helm', syllables: ['Helm'], emoji: '🪖' },
    { word: 'Brille', syllables: ['Bril', 'le'], emoji: '👓' },
    { word: 'Uhr', syllables: ['Uhr'], emoji: '⌚' },
    { word: 'Ring', syllables: ['Ring'], emoji: '💍' },
    { word: 'Kette', syllables: ['Ket', 'te'], emoji: '⛓️' },
    { word: 'Krone', syllables: ['Kro', 'ne'], emoji: '👑' },
    { word: 'Zepter', syllables: ['Zep', 'ter'], emoji: '🪄' },
    { word: 'Schwert', syllables: ['Schwert'], emoji: '⚔️' },
    { word: 'Schild', syllables: ['Schild'], emoji: '🛡️' },
    { word: 'Bogen', syllables: ['Bo', 'gen'], emoji: '🏹' },
    { word: 'Pfeil', syllables: ['Pfeil'], emoji: '💘' },
    { word: 'Axt', syllables: ['Axt'], emoji: '🪓' },
    { word: 'Hammer', syllables: ['Ham', 'mer'], emoji: '🔨' },
    { word: 'Säge', syllables: ['Sä', 'ge'], emoji: '🪚' },
    { word: 'Zange', syllables: ['Zan', 'ge'], emoji: '🔧' },
    { word: 'Nagel', syllables: ['Na', 'gel'], emoji: '🔩' },
    { word: 'Schraube', syllables: ['Schrau', 'be'], emoji: '🪛' },
    { word: 'Pinsel', syllables: ['Pin', 'sel'], emoji: '🖌️' },
    { word: 'Farbe', syllables: ['Far', 'be'], emoji: '🎨' },
    { word: 'Stift', syllables: ['Stift'], emoji: '✏️' },
    { word: 'Papier', syllables: ['Pa', 'pier'], emoji: '📄' },
    { word: 'Buch', syllables: ['Buch'], emoji: '📖' },
    { word: 'Heft', syllables: ['Heft'], emoji: '📓' },
    { word: 'Schere', syllables: ['Sche', 're'], emoji: '✂️' },
    { word: 'Lineal', syllables: ['Li', 'ne', 'al'], emoji: '📏' },
    { word: 'Kleber', syllables: ['Kle', 'ber'], emoji: '🧪' },
    { word: 'Tafel', syllables: ['Ta', 'fel'], emoji: '📋' },
    { word: 'Kreide', syllables: ['Krei', 'de'], emoji: '🖍️' },
    { word: 'Lampe', syllables: ['Lam', 'pe'], emoji: '💡' },
    { word: 'Kerze', syllables: ['Ker', 'ze'], emoji: '🕯️' },
    { word: 'Seife', syllables: ['Sei', 'fe'], emoji: '🧼' },
    { word: 'Kamm', syllables: ['Kamm'], emoji: '🪮' },
    { word: 'Bürste', syllables: ['Bür', 'ste'], emoji: '🪮' },
    { word: 'Tasse', syllables: ['Tas', 'se'], emoji: '☕' },
    { word: 'Teller', syllables: ['Tel', 'ler'], emoji: '🍽️' },
    { word: 'Löffel', syllables: ['Löf', 'fel'], emoji: '🥄' },
    { word: 'Gabel', syllables: ['Ga', 'bel'], emoji: '🍴' },
    { word: 'Messer', syllables: ['Mes', 'ser'], emoji: '🔪' },
    { word: 'Pfanne', syllables: ['Pfan', 'ne'], emoji: '🍳' },
    { word: 'Topf', syllables: ['Topf'], emoji: '🍲' },
    { word: 'Ofen', syllables: ['O', 'fen'], emoji: '🔥' },
    { word: 'Besen', syllables: ['Be', 'sen'], emoji: '🧹' },
    { word: 'Eimer', syllables: ['Ei', 'mer'], emoji: '🪣' },
    { word: 'Gießkanne', syllables: ['Gieß', 'kan', 'ne'], emoji: '🪴' },
    { word: 'Schaufel', syllables: ['Schau', 'fel'], emoji: '🪵' },
    { word: 'Rechen', syllables: ['Re', 'chen'], emoji: '🪵' },
    { word: 'Schirm', syllables: ['Schirm'], emoji: '☂️' },
    { word: 'Sonne', syllables: ['Son', 'ne'], emoji: '☀️' },
    { word: 'Wolke', syllables: ['Wol', 'ke'], emoji: '☁️' },
    { word: 'Blitz', syllables: ['Blitz'], emoji: '⚡' },
    { word: 'Donner', syllables: ['Don', 'ner'], emoji: '⛈️' },
    { word: 'Schnee', syllables: ['Schnee'], emoji: '❄️' },
    { word: 'Hagel', syllables: ['Ha', 'gel'], emoji: '🌨️' },
    { word: 'Eis', syllables: ['Eis'], emoji: '🧊' },
    { word: 'Feuer', syllables: ['Feu', 'er'], emoji: '🔥' },
    { word: 'Rauch', syllables: ['Rauch'], emoji: '💨' },
    { word: 'Schmetterling', syllables: ['Schmet', 'ter', 'ling'], emoji: '🦋' },
    { word: 'Hubschrauber', syllables: ['Hub', 'schrau', 'ber'], emoji: '🚁' },
    { word: 'Feuerwehr', syllables: ['Feu', 'er', 'wehr'], emoji: '🚒' },
    { word: 'Polizistin', syllables: ['Po', 'li', 'zis', 'tin'], emoji: '👮‍♀️' },
    { word: 'Lokomotive', syllables: ['Lo', 'ko', 'mo', 'ti', 've'], emoji: '🚂' },
    { word: 'Elefant', syllables: ['E', 'le', 'fant'], emoji: '🐘' },
    { word: 'Krokodil', syllables: ['Kro', 'ko', 'dil'], emoji: '🐊' },
    { word: 'Schildkröte', syllables: ['Schild', 'krö', 'te'], emoji: '🐢' },
    { word: 'Papagei', syllables: ['Pa', 'pa', 'gei'], emoji: '🦜' },
    { word: 'Dinosaurier', syllables: ['Di', 'no', 'sau', 'ri', 'er'], emoji: '🦖' },
    { word: 'Regenbogen', syllables: ['Re', 'gen', 'bo', 'gen'], emoji: '🌈' },
    { word: 'Marienkäfer', syllables: ['Ma', 'ri', 'en', 'kä', 'fer'], emoji: '🐞' },
    { word: 'Sonnenblume', syllables: ['Son', 'nen', 'blu', 'me'], emoji: '🌻' },
    { word: 'Erdbeerkuchen', syllables: ['Erd', 'beer', 'ku', 'chen'], emoji: '🍰' },
    { word: 'Regenschirm', syllables: ['Re', 'gen', 'schirm'], emoji: '☂️' },
    { word: 'Schokolade', syllables: ['Scho', 'ko', 'la', 'de'], emoji: '🍫' },
    { word: 'Abenteuer', syllables: ['A', 'ben', 'teu', 'er'], emoji: '🧭' },
    { word: 'Zahnbürste', syllables: ['Zahn', 'bür', 'ste'], emoji: '🪥' },
    { word: 'Kindergarten', syllables: ['Kin', 'der', 'gar', 'ten'], emoji: '🏫' },
    { word: 'Fahrradfahren', syllables: ['Fahr', 'rad', 'fah', 'ren'], emoji: '🚲' },
    { word: 'Wassertropfen', syllables: ['Was', 'ser', 'trop', 'fen'], emoji: '💧' },
    { word: 'Eichhörnchen', syllables: ['Eich', 'hörn', 'chen'], emoji: '🐿️' }
];

export const expandedRhymeData: RhymeItem[] = [
    { word: 'Haus', rhyme: 'Maus', distractors: ['Hund', 'Katze', 'Auto'], emoji: '🏠' },
    { word: 'Mond', rhyme: 'Hund', distractors: ['Sonne', 'Stern', 'Wolke'], emoji: '🌙' }, // Mond-Hund is weak but common for kids
    { word: 'Baum', rhyme: 'Traum', distractors: ['Blatt', 'Zweig', 'Wiese'], emoji: '🌳' },
    { word: 'Hand', rhyme: 'Sand', distractors: ['Finger', 'Fuß', 'Arm'], emoji: '✋' },
    { word: 'Brot', rhyme: 'Rot', distractors: ['Gelb', 'Blau', 'Grün'], emoji: '🍞' },
    { word: 'Schuh', rhyme: 'Kuh', distractors: ['Socke', 'Hose', 'Jacke'], emoji: '👞' },
    { word: 'Löwe', rhyme: 'Möwe', distractors: ['Tiger', 'Bär', 'Wolf'], emoji: '🦁' },
    { word: 'Ball', rhyme: 'Knall', distractors: ['Spiel', 'Spaß', 'Tor'], emoji: '⚽' },
    { word: 'Hut', rhyme: 'Gut', distractors: ['Schlecht', 'Böse', 'Nett'], emoji: '🎩' },
    { word: 'Rose', rhyme: 'Hose', distractors: ['Blume', 'Blatt', 'Baum'], emoji: '🌹' },
    { word: 'Dach', rhyme: 'Fach', distractors: ['Haus', 'Tür', 'Fenster'], emoji: '🏠' },
    { word: 'Licht', rhyme: 'Sicht', distractors: ['Dunkel', 'Farbe', 'Form'], emoji: '💡' },
    { word: 'Meer', rhyme: 'Heer', distractors: ['Land', 'Sand', 'Strand'], emoji: '🌊' },
    { word: 'Wand', rhyme: 'Land', distractors: ['Zimmer', 'Boden', 'Decke'], emoji: '🧱' },
    { word: 'Kamm', rhyme: 'Lamm', distractors: ['Bürste', 'Haare', 'Kopf'], emoji: '🪮' },
    { word: 'Tisch', rhyme: 'Fisch', distractors: ['Stuhl', 'Schrank', 'Bett'], emoji: '🪑' },
    { word: 'Kopf', rhyme: 'Topf', distractors: ['Hut', 'Mütze', 'Helm'], emoji: '🧒' },
    { word: 'Herz', rhyme: 'Schmerz', distractors: ['Liebe', 'Glück', 'Freude'], emoji: '❤️' },
    { word: 'Sinn', rhyme: 'Gewinn', distractors: ['Verlust', 'Ende', 'Start'], emoji: '🧠' },
    { word: 'Kind', rhyme: 'Wind', distractors: ['Baby', 'Eltern', 'Oma'], emoji: '👶' },
    { word: 'Stein', rhyme: 'Bein', distractors: ['Fels', 'Sand', 'Staub'], emoji: '🪨' },
    { word: 'Eis', rhyme: 'Reis', distractors: ['Heiß', 'Kalt', 'Lau'], emoji: '🍦' },
    { word: 'Blau', rhyme: 'Grau', distractors: ['Rot', 'Gelb', 'Grün'], emoji: '🟦' },
    { word: 'Fuchs', rhyme: 'Luchs', distractors: ['Hund', 'Wolf', 'Bär'], emoji: '🦊' },
    { word: 'Gans', rhyme: 'Tanz', distractors: ['Ente', 'Huhn', 'Vogel'], emoji: '🪿' },
    { word: 'Hase', rhyme: 'Nase', distractors: ['Ohr', 'Auge', 'Mund'], emoji: '🐰' },
    { word: 'Regen', rhyme: 'Segen', distractors: ['Sonne', 'Wind', 'Schnee'], emoji: '🌧️' },
    { word: 'Stern', rhyme: 'Kern', distractors: ['Mond', 'Sonne', 'Wolke'], emoji: '⭐' },
    { word: 'Tier', rhyme: 'Bier', distractors: ['Mensch', 'Pflanze', 'Ding'], emoji: '🐾' },
    { word: 'Wein', rhyme: 'Schwein', distractors: ['Wasser', 'Saft', 'Milch'], emoji: '🍇' },
    { word: 'Zebra', rhyme: 'Kobra', distractors: ['Tiger', 'Löwe', 'Giraffe'], emoji: '🦓' },
    { word: 'Maus', rhyme: 'laus', distractors: ['Käse', 'Loch', 'Falle'], emoji: '🐭' },
    { word: 'Torte', rhyme: 'Pforte', distractors: ['Kuchen', 'Keks', 'Eis'], emoji: '🎂' },
    { word: 'Wald', rhyme: 'Kalt', distractors: ['Warm', 'Heiß', 'Naß'], emoji: '🌲' },
    { word: 'Zeit', rhyme: 'Breit', distractors: ['Schmal', 'Kurz', 'Lang'], emoji: '⌚' },
    { word: 'Jahr', rhyme: 'Paar', distractors: ['Eins', 'Drei', 'Vier'], emoji: '📅' },
    { word: 'Tor', rhyme: 'Ohr', distractors: ['Auge', 'Nase', 'Mund'], emoji: '🚪' },
    { word: 'Sohn', rhyme: 'Bohn', distractors: ['Tochter', 'Mutter', 'Vater'], emoji: '👦' },
    { word: 'Lied', rhyme: 'Glied', distractors: ['Musik', 'Tanz', 'Spiel'], emoji: '🎶' },
    { word: 'Sonne', rhyme: 'Wonne', distractors: ['Hitze', 'Licht', 'Himmel'], emoji: '☀️' }
];

export const expandedGapData: GapItem[] = [
    { sentence: ['Der', 'Hund', 'bellt', '.'], answer: 'bellt', options: ['bellt', 'singt', 'fliegt'], emoji: '🐕' },
    { sentence: ['Die', 'Sonne', 'scheint', '.'], answer: 'scheint', options: ['scheint', 'regnet', 'schneit'], emoji: '☀️' },
    { sentence: ['Ich', 'esse', 'einen', 'Apfel', '.'], answer: 'esse', options: ['esse', 'trinke', 'fahre'], emoji: '🍎' },
    { sentence: ['Das', 'Kind', 'spielt', 'im', 'Garten', '.'], answer: 'spielt', options: ['spielt', 'schläft', 'liest'], emoji: '👶' },
    { sentence: ['Der', 'Vogel', 'fliegt', 'hoch', '.'], answer: 'fliegt', options: ['fliegt', 'schwimmt', 'läuft'], emoji: '🐦' },
    { sentence: ['Wir', 'lesen', 'ein', 'spannendes', 'Buch', '.'], answer: 'lesen', options: ['lesen', 'malen', 'bauen'], emoji: '📖' },
    { sentence: ['Das', 'Auto', 'fährt', 'schnell', '.'], answer: 'fährt', options: ['fährt', 'geht', 'springt'], emoji: '🚗' },
    { sentence: ['Mama', 'kocht', 'eine', 'leckere', 'Suppe', '.'], answer: 'kocht', options: ['kocht', 'backt', 'wäscht'], emoji: '🍲' },
    { sentence: ['Papa', 'arbeitet', 'im', 'Büro', '.'], answer: 'arbeitet', options: ['arbeitet', 'spielt', 'tanzt'], emoji: '👨' },
    { sentence: ['Die', 'Katze', 'schläft', 'auf', 'dem', 'Sofa', '.'], answer: 'schläft', options: ['schläft', 'tanzt', 'schreit'], emoji: '🐈' },
    { sentence: ['Der', 'Fisch', 'schwimmt', 'im', 'Wasser', '.'], answer: 'schwimmt', options: ['schwimmt', 'fliegt', 'klettert'], emoji: '🐟' },
    { sentence: ['Ich', 'trinke', 'ein', 'Glas', 'Milch', '.'], answer: 'trinke', options: ['trinke', 'esse', 'werfe'], emoji: '🥛' },
    { sentence: ['Die', 'Blume', 'blüht', 'im', 'Frühling', '.'], answer: 'blüht', options: ['blüht', 'welkt', 'friert'], emoji: '🌸' },
    { sentence: ['Der', 'Zug', 'kommt', 'pünktlich', 'an', '.'], answer: 'kommt', options: ['kommt', 'geht', 'bleibt'], emoji: '🚂' },
    { sentence: ['Wir', 'gehen', 'heute', 'in', 'den', 'Zoo', '.'], answer: 'gehen', options: ['gehen', 'fliegen', 'reiten'], emoji: '🦁' },
    { sentence: ['Das', 'Haus', 'ist', 'sehr', 'groß', '.'], answer: 'ist', options: ['ist', 'hat', 'wird'], emoji: '🏠' },
    { sentence: ['Der', 'Apfel', 'schmeckt', 'sehr', 'süß', '.'], answer: 'schmeckt', options: ['schmeckt', 'sieht', 'riecht'], emoji: '🍎' },
    { sentence: ['Du', 'hast', 'viele', 'bunte', 'Stifte', '.'], answer: 'hast', options: ['hast', 'bist', 'darfst'], emoji: '✏️' },
    { sentence: ['Der', 'Elefant', 'ist', 'ein', 'großes', 'Tier', '.'], answer: 'ist', options: ['ist', 'hat', 'macht'], emoji: '🐘' },
    { sentence: ['Der', 'Himmel', 'ist', 'heute', 'blau', '.'], answer: 'ist', options: ['ist', 'wird', 'macht'], emoji: '🌌' },
    { sentence: ['Ich', 'gehe', 'in', 'die', 'Schule', '.'], answer: 'gehe', options: ['gehe', 'laufe', 'schwimme'], emoji: '🏫' },
    { sentence: ['Wir', 'spielen', 'im', 'Garten', '.'], answer: 'spielen', options: ['spielen', 'kochen', 'schlafen'], emoji: '🏡' },
    { sentence: ['Du', 'hast', 'einen', 'bunten', 'Ball', '.'], answer: 'hast', options: ['hast', 'bist', 'gibst'], emoji: '⚽' },
    { sentence: ['Die', 'Katze', 'schläft', 'auf', 'dem', 'Sofa', '.'], answer: 'schläft', options: ['schläft', 'tanzt', 'singt'], emoji: '🐱' },
    { sentence: ['Der', 'Hund', 'bellt', 'laut', '.'], answer: 'bellt', options: ['bellt', 'lacht', 'weint'], emoji: '🐶' },
    { sentence: ['Eis', 'schmeckt', 'sehr', 'gut', '.'], answer: 'schmeckt', options: ['schmeckt', 'sieht', 'hört'], emoji: '🍦' },
    { sentence: ['Vögel', 'fliegen', 'hoch', 'am', 'Himmel', '.'], answer: 'fliegen', options: ['fliegen', 'schwimmen', 'krabbeln'], emoji: '🐦' },
    { sentence: ['Fische', 'schwimmen', 'im', 'tiefen', 'Wasser', '.'], answer: 'schwimmen', options: ['schwimmen', 'rennen', 'klettern'], emoji: '🐟' },
    { sentence: ['Die', 'Sonne', 'scheint', 'warm', '.'], answer: 'scheint', options: ['scheint', 'regnet', 'schneit'], emoji: '☀️' },
    { sentence: ['Es', 'regnet', 'aus', 'den', 'Wolken', '.'], answer: 'regnet', options: ['regnet', 'blitzt', 'donnert'], emoji: '🌧️' },
    { sentence: ['Ich', 'mag', 'rote', 'Äpfel', '.'], answer: 'mag', options: ['mag', 'hasse', 'esse'], emoji: '🍎' },
    { sentence: ['Wir', 'essen', 'gerne', 'Pizza', '.'], answer: 'essen', options: ['essen', 'trinken', 'backen'], emoji: '🍕' },
    { sentence: ['Mutter', 'kocht', 'eine', 'leckere', 'Suppe', '.'], answer: 'kocht', options: ['kocht', 'räumt', 'wäscht'], emoji: '🍲' },
    { sentence: ['Vater', 'liest', 'ein', 'spannendes', 'Buch', '.'], answer: 'liest', options: ['liest', 'schreibt', 'malt'], emoji: '📖' },
    { sentence: ['Das', 'Kind', 'lacht', 'fröhlich', '.'], answer: 'lacht', options: ['lacht', 'weint', 'schreit'], emoji: '👶' },
    { sentence: ['Das', 'Auto', 'fährt', 'schnell', '.'], answer: 'fährt', options: ['fährt', 'fliegt', 'hüpft'], emoji: '🚗' },
    { sentence: ['Der', 'Bus', 'hält', 'an', 'der', 'Haltestelle', '.'], answer: 'hält', options: ['hält', 'fährt', 'wartet'], emoji: '🚌' },
    { sentence: ['Ich', 'putze', 'meine', 'Zähne', '.'], answer: 'putze', options: ['putze', 'wasche', 'kämme'], emoji: '🪥' },
    { sentence: ['Wir', 'waschen', 'unsere', 'Hände', '.'], answer: 'waschen', options: ['waschen', 'trocknen', 'cremen'], emoji: '🧼' },
    { sentence: ['Sie', 'malt', 'ein', 'schönes', 'Bild', '.'], answer: 'malt', options: ['malt', 'zeichnet', 'klebt'], emoji: '🎨' },
    { sentence: ['Er', 'baut', 'einen', 'hohen', 'Turm', '.'], answer: 'baut', options: ['baut', 'reißt', 'stellt'], emoji: '🧱' },
    { sentence: ['Der', 'Hase', 'hoppelt', 'über', 'die', 'Wiese', '.'], answer: 'hoppelt', options: ['hoppelt', 'rennt', 'schleicht'], emoji: '🐰' },
    { sentence: ['Die', 'Maus', 'frisst', 'den', 'Käse', '.'], answer: 'frisst', options: ['frisst', 'knabbert', 'stiehlt'], emoji: '🐭' },
    { sentence: ['Pferde', 'galoppieren', 'auf', 'dem', 'Feld', '.'], answer: 'galoppieren', options: ['galoppieren', 'traben', 'gehen'], emoji: '🐎' },
    { sentence: ['Kühe', 'geben', 'uns', 'Milch', '.'], answer: 'geben', options: ['geben', 'holen', 'trinken'], emoji: '🐄' },
    { sentence: ['Schafe', 'tragen', 'warme', 'Wolle', '.'], answer: 'tragen', options: ['tragen', 'haben', 'geben'], emoji: '🐑' },
    { sentence: ['Schweine', 'wälzen', 'sich', 'im', 'Matsch', '.'], answer: 'wälzen', options: ['wälzen', 'liegen', 'spielen'], emoji: '🐖' },
    { sentence: ['Der', 'Hahn', 'kräht', 'früh', 'am', 'Morgen', '.'], answer: 'kräht', options: ['kräht', 'singt', 'ruft'], emoji: '🐓' },
    { sentence: ['Bienen', 'sammeln', 'süßen', 'Honig', '.'], answer: 'sammeln', options: ['sammeln', 'machen', 'suchen'], emoji: '🐝' },
    { sentence: ['Spinne', 'webt', 'ein', 'großes', 'Netz', '.'], answer: 'webt', options: ['webt', 'spinnt', 'baut'], emoji: '🕷️' },
    { sentence: ['Der', 'Frosch', 'quakt', 'im', 'Teich', '.'], answer: 'quakt', options: ['quakt', 'springt', 'taucht'], emoji: '🐸' },
    { sentence: ['Schmetterling', 'fliegt', 'von', 'Blume', 'zu', 'Blume', '.'], answer: 'fliegt', options: ['fliegt', 'tanzt', 'sitzt'], emoji: '🦋' },
    { sentence: ['Ameise', 'trägt', 'ein', 'schweres', 'Blatt', '.'], answer: 'trägt', options: ['trägt', 'schiebt', 'zieht'], emoji: '🐜' },
    { sentence: ['Wir', 'sehen', 'mit', 'unseren', 'Augen', '.'], answer: 'sehen', options: ['sehen', 'hören', 'riechen'], emoji: '👁️' },
    { sentence: ['Wir', 'hören', 'mit', 'unseren', 'Ohren', '.'], answer: 'hören', options: ['hören', 'sehen', 'fühlen'], emoji: '👂' },
    { sentence: ['Wir', 'riechen', 'mit', 'unserer', 'Nase', '.'], answer: 'riechen', options: ['riechen', 'schmecken', 'atmen'], emoji: '👃' },
    { sentence: ['Wir', 'atmen', 'die', 'frische', 'Luft', '.'], answer: 'atmen', options: ['atmen', 'pusten', 'saugen'], emoji: '🌬️' },
    { sentence: ['Ich', 'schreibe', 'mit', 'dem', 'Bleistift', '.'], answer: 'schreibe', options: ['schreibe', 'male', 'radiere'], emoji: '✏️' },
    { sentence: ['Du', 'schneidest', 'mit', 'der', 'Schere', '.'], answer: 'schneidest', options: ['schneidest', 'reißt', 'faltest'], emoji: '✂️' },
    { sentence: ['Wir', 'kleben', 'mit', 'dem', 'Kleber', '.'], answer: 'kleben', options: ['kleben', 'heften', 'binden'], emoji: '🧪' },
    { sentence: ['Der', 'Lehrer', 'erklärt', 'die', 'Aufgabe', '.'], answer: 'erklärt', options: ['erklärt', 'schreibt', 'liest'], emoji: '👨‍🏫' },
    { sentence: ['Die', 'Kinder', 'lernen', 'rechnen', '.'], answer: 'lernen', options: ['lernen', 'üben', 'spielen'], emoji: '🧮' },
    { sentence: ['Wir', 'singen', 'ein', 'lustiges', 'Lied', '.'], answer: 'singen', options: ['singen', 'pfeifen', 'summen'], emoji: '🎵' },
    { sentence: ['Musik', 'macht', 'uns', 'Freude', '.'], answer: 'macht', options: ['macht', 'gibt', 'bringt'], emoji: '🎶' },
    { sentence: ['Tanzen', 'macht', 'sehr', 'viel', 'Spaß', '.'], answer: 'macht', options: ['macht', 'geht', 'sieht'], emoji: '💃' },
    { sentence: ['Laufen', 'hält', 'unsere', 'Körper', 'fit', '.'], answer: 'hält', options: ['hält', 'macht', 'bringt'], emoji: '🏃' },
    { sentence: ['Springen', 'macht', 'starke', 'Beine', '.'], answer: 'macht', options: ['macht', 'gibt', 'braucht'], emoji: '🦵' },
    { sentence: ['Klettern', 'erfordert', 'viel', 'Kraft', '.'], answer: 'erfordert', options: ['erfordert', 'braucht', 'gibt'], emoji: '🧗' },
    { sentence: ['Schwimmen', 'im', 'See', 'ist', 'erfrischend', '.'], answer: 'ist', options: ['ist', 'wird', 'macht'], emoji: '🏊' },
    { sentence: ['Fahrradfahren', 'macht', 'ganz', 'schön', 'schnell', '.'], answer: 'macht', options: ['macht', 'fährt', 'geht'], emoji: '🚲' }
];

export const expandedWordListData: WordMatchItem[] = [
    { word: 'Affe', options: ['Affe', 'Löwe', 'Tiger'], emoji: '🐒' },
    { word: 'Ball', options: ['Ball', 'Buch', 'Brot'], emoji: '⚽' },
    { word: 'Cello', options: ['Cello', 'Geige', 'Klavier'], emoji: '🎻' },
    { word: 'Delfin', options: ['Delfin', 'Wal', 'Hai'], emoji: '🐬' },
    { word: 'Ente', options: ['Ente', 'Gans', 'Huhn'], emoji: '🦆' },
    { word: 'Fisch', options: ['Fisch', 'Vogel', 'Hund'], emoji: '🐟' },
    { word: 'Giraffe', options: ['Giraffe', 'Zebra', 'Elefant'], emoji: '🦒' },
    { word: 'Hase', options: ['Hase', 'Maus', 'Katze'], emoji: '🐰' },
    { word: 'Igel', options: ['Igel', 'Maus', 'Ratte'], emoji: '🦔' },
    { word: 'Joghurt', options: ['Joghurt', 'Milch', 'Käse'], emoji: '🍦' },
    { word: 'Krokodil', options: ['Krokodil', 'Echse', 'Schlange'], emoji: '🐊' },
    { word: 'Löwe', options: ['Löwe', 'Tiger', 'Bär'], emoji: '🦁' },
    { word: 'Maus', options: ['Maus', 'Ratte', 'Igel'], emoji: '🐭' },
    { word: 'Nashorn', options: ['Nashorn', 'Elefant', 'Flusspferd'], emoji: '🦏' },
    { word: 'Oktopus', options: ['Oktopus', 'Fisch', 'Qualle'], emoji: '🐙' },
    { word: 'Papagei', options: ['Papagei', 'Eule', 'Adler'], emoji: '🦜' },
    { word: 'Qualle', options: ['Qualle', 'Fisch', 'Hai'], emoji: '🪼' },
    { word: 'Reh', options: ['Reh', 'Hirsch', 'Elch'], emoji: '🦌' },
    { word: 'Schildkröte', options: ['Schildkröte', 'Krabbe', 'Schnecke'], emoji: '🐢' },
    { word: 'Tiger', options: ['Tiger', 'Löwe', 'Leopard'], emoji: '🐅' },
    { word: 'Uhu', options: ['Uhu', 'Eule', 'Adler'], emoji: '🦉' },
    { word: 'Vogel', options: ['Vogel', 'Insekt', 'Fisch'], emoji: '🐦' },
    { word: 'Wolf', options: ['Wolf', 'Hund', 'Fuchs'], emoji: '🐺' },
    { word: 'Xylophon', options: ['Xylophon', 'Flöte', 'Trommel'], emoji: '🎹' },
    { word: 'Yeti', options: ['Yeti', 'Monster', 'Bär'], emoji: '👹' },
    { word: 'Zebra', options: ['Zebra', 'Esel', 'Pferd'], emoji: '🦓' },
    { word: 'Ameise', options: ['Ameise', 'Biene', 'Wespe'], emoji: '🐜' },
    { word: 'Biene', options: ['Biene', 'Wespe', 'Fliege'], emoji: '🐝' },
    { word: 'Chamäleon', options: ['Chamäleon', 'Echse', 'Frosch'], emoji: '🦎' },
    { word: 'Dachs', options: ['Dachs', 'Fuchs', 'Bär'], emoji: '🦡' },
    { word: 'Käfer', options: ['Käfer', 'Biene', 'Fliege'], emoji: '🐞' },
    { word: 'Wurm', options: ['Wurm', 'Schlange', 'Raupe'], emoji: '🪱' },
    { word: 'Ratte', options: ['Ratte', 'Maus', 'Hamster'], emoji: '🐀' },
    { word: 'Hamster', options: ['Hamster', 'Maus', 'Meerschweinchen'], emoji: '🐹' },
    { word: 'Meerschweinchen', options: ['Meerschweinchen', 'Kaninchen', 'Hamster'], emoji: '🐹' },
    { word: 'Kaninchen', options: ['Kaninchen', 'Hase', 'Hamster'], emoji: '🐰' },
    { word: 'Esel', options: ['Esel', 'Pferd', 'Pony'], emoji: '🫏' },
    { word: 'Pferd', options: ['Pferd', 'Esel', 'Zebra'], emoji: '🐎' },
    { word: 'Pony', options: ['Pony', 'Pferd', 'Esel'], emoji: '🐴' },
    { word: 'Schaf', options: ['Schaf', 'Ziege', 'Lamm'], emoji: '🐑' },
    { word: 'Ziege', options: ['Ziege', 'Schaf', 'Reh'], emoji: '🐐' },
    { word: 'Lamm', options: ['Lamm', 'Schaf', 'Kitz'], emoji: '🐑' },
    { word: 'Kalb', options: ['Kalb', 'Kuh', 'Fohlen'], emoji: '🐮' },
    { word: 'Fohlen', options: ['Fohlen', 'Pferd', 'Kalb'], emoji: '🐴' },
    { word: 'Küken', options: ['Küken', 'Huhn', 'Ente'], emoji: '🐥' },
    { word: 'Hahn', options: ['Hahn', 'Huhn', 'Pute'], emoji: '🐓' },
    { word: 'Huhn', options: ['Huhn', 'Hahn', 'Ente'], emoji: '🐔' },
    { word: 'Pute', options: ['Pute', 'Huhn', 'Gans'], emoji: '🦃' },
    { word: 'Gans', options: ['Gans', 'Ente', 'Schwan'], emoji: '🪿' },
    { word: 'Schwan', options: ['Schwan', 'Gans', 'Ente'], emoji: '🦢' },
    { word: 'Pelikan', options: ['Pelikan', 'Flamingo', 'Storch'], emoji: '🦢' },
    { word: 'Flamingo', options: ['Flamingo', 'Pelikan', 'Storch'], emoji: '🦩' },
    { word: 'Storch', options: ['Storch', 'Kranich', 'Reiher'], emoji: '🦢' },
    { word: 'Kranich', options: ['Kranich', 'Storch', 'Reiher'], emoji: '🦢' },
    { word: 'Eule', options: ['Eule', 'Uhu', 'Falke'], emoji: '🦉' },
    { word: 'Falke', options: ['Falke', 'Adler', 'Bussard'], emoji: '🦅' },
    { word: 'Adler', options: ['Adler', 'Falke', 'Geier'], emoji: '🦅' },
    { word: 'Geier', options: ['Geier', 'Adler', 'Rabe'], emoji: '🦅' },
    { word: 'Rabe', options: ['Rabe', 'Krähe', 'Dohle'], emoji: '🐦‍⬛' },
    { word: 'Krähe', options: ['Krähe', 'Rabe', 'Elster'], emoji: '🐦‍⬛' },
    { word: 'Elster', options: ['Elster', 'Eichelhäher', 'Amsel'], emoji: '🐦' },
    { word: 'Amsel', options: ['Amsel', 'Drossel', 'Sperling'], emoji: '🐦' },
    { word: 'Sperling', options: ['Sperling', 'Meise', 'Fink'], emoji: '🐦' },
    { word: 'Meise', options: ['Meise', 'Spatz', 'Rotkehlchen'], emoji: '🐦' },
    { word: 'Rotkehlchen', options: ['Rotkehlchen', 'Nachtigall', 'Lerche'], emoji: '🐦' },
    { word: 'Specht', options: ['Specht', 'Kleiber', 'Baumläufer'], emoji: '🐦' },
    { word: 'Schwalbe', options: ['Schwalbe', 'Mauersegler', 'Drossel'], emoji: '🐦' },
    { word: 'Fledermaus', options: ['Fledermaus', 'Vampir', 'Maus'], emoji: '🦇' },
    { word: 'Wal', options: ['Wal', 'Delfin', 'Hai'], emoji: '🐋' },
    { word: 'Hai', options: ['Hai', 'Wal', 'Delfin'], emoji: '🦈' },
    { word: 'Rochen', options: ['Rochen', 'Hai', 'Fisch'], emoji: '🐟' },
    { word: 'Seepferdchen', options: ['Seepferdchen', 'Nadel fisch', 'Fisch'], emoji: '🧜' },
    { word: 'Krabbe', options: ['Krabbe', 'Hummer', 'Garnele'], emoji: '🦀' },
    { word: 'Hummer', options: ['Hummer', 'Krabbe', 'Languste'], emoji: '🦞' },
    { word: 'Garnele', options: ['Garnele', 'Scampi', 'Krabbe'], emoji: '🦐' },
    { word: 'Muschel', options: ['Muschel', 'Schnecke', 'Auster'], emoji: '🐚' },
    { word: 'Schnecke', options: ['Schnecke', 'Wurm', 'Muschel'], emoji: '🐌' },
    { word: 'Biene', options: ['Biene', 'Wespe', 'Hummel'], emoji: '🐝' },
    { word: 'Wespe', options: ['Wespe', 'Biene', 'Hornisse'], emoji: '🐝' },
    { word: 'Hummel', options: ['Hummel', 'Biene', 'Wespe'], emoji: '🐝' }
];

export const expandedUnscrambleData: UnscrambleItem[] = [
    { word: 'HAUS', emoji: '🏠' },
    { word: 'MAUS', emoji: '🐭' },
    { word: 'BAUM', emoji: '🌳' },
    { word: 'AUTO', emoji: '🚗' },
    { word: 'BROT', emoji: '🍞' },
    { word: 'FISCH', emoji: '🐟' },
    { word: 'HUND', emoji: '🐕' },
    { word: 'KATZE', emoji: '🐈' },
    { word: 'APFEL', emoji: '🍎' },
    { word: 'BLUME', emoji: '🌸' },
    { word: 'SONNE', emoji: '☀️' },
    { word: 'MONSTER', emoji: '👹' },
    { word: 'STERN', emoji: '⭐' },
    { word: 'VOGEL', emoji: '🐦' },
    { word: 'REGEN', emoji: '🌧️' },
    { word: 'SCHNEE', emoji: '❄️' },
    { word: 'WOLKE', emoji: '☁️' },
    { word: 'MOND', emoji: '🌙' },
    { word: 'ERDE', emoji: '🌍' },
    { word: 'FEUER', emoji: '🔥' },
    { word: 'WASSER', emoji: '💧' },
    { word: 'WIND', emoji: '🌬️' },
    { word: 'ZUG', emoji: '🚂' },
    { word: 'BUS', emoji: '🚌' },
    { word: 'RAD', emoji: '🚲' },
    { word: 'KUCHEN', emoji: '🍰' },
    { word: 'KEKS', emoji: '🍪' },
    { word: 'MILCH', emoji: '🥛' },
    { word: 'SAFT', emoji: '🧃' },
    { word: 'KASSE', emoji: '💰' },
    { word: 'GELD', emoji: '💶' },
    { word: 'TISCH', emoji: '🪑' },
    { word: 'STUHL', emoji: '🪑' },
    { word: 'BETT', emoji: '🛌' },
    { word: 'LAMPE', emoji: '💡' },
    { word: 'TÜR', emoji: '🚪' },
    { word: 'FENSTER', emoji: '🪟' },
    { word: 'DACH', emoji: '🏠' },
    { word: 'KELLER', emoji: '📦' },
    { word: 'TREPPE', emoji: '🪜' },
    { word: 'BAD', emoji: '🛀' },
    { word: 'SEIFE', emoji: '🧼' },
    { word: 'TASSE', emoji: '☕' },
    { word: 'TELLER', emoji: '🍽️' },
    { word: 'LÖFFEL', emoji: '🥄' },
    { word: 'GABEL', emoji: '🍴' },
    { word: 'MESSER', emoji: '🔪' },
    { word: 'TOPF', emoji: '🍲' },
    { word: 'PFANNE', emoji: '🍳' },
    { word: 'OFEN', emoji: '🔥' },
    { word: 'BESEN', emoji: '🧹' },
    { word: 'EIMER', emoji: '🪣' },
    { word: 'GARTEN', emoji: '🏡' },
    { word: 'BLATT', emoji: '🍃' },
    { word: 'AST', emoji: '🪵' },
    { word: 'FELS', emoji: '🪨' },
    { word: 'SAND', emoji: '🏖️' },
    { word: 'INSEL', emoji: '🏝️' },
    { word: 'MEER', emoji: '🌊' },
    { word: 'WALD', emoji: '🌲' },
    { word: 'BERG', emoji: '⛰️' },
    { word: 'TAL', emoji: '🏞️' },
    { word: 'WEG', emoji: '🛤️' },
    { word: 'STADT', emoji: '🏙️' },
    { word: 'DORF', emoji: '🏘️' },
    { word: 'LAND', emoji: '🗺️' }
];

export const expandedFishingData: FishingItem[] = [
    { target: 'HUND', pool: ['HUND', 'HASE', 'HAUS', 'HAND'], emoji: '🐕' },
    { target: 'KATZE', pool: ['KATZE', 'KUSS', 'KAMM', 'KOHL'], emoji: '🐈' },
    { target: 'AUTO', pool: ['AUTO', 'AUGE', 'AMEISE', 'APFEL'], emoji: '🚗' },
    { target: 'BAUM', pool: ['BAUM', 'BALL', 'BART', 'BEIN'], emoji: '🌳' },
    { target: 'BLUME', pool: ['BLUME', 'BLATT', 'BOCK', 'BURG'], emoji: '🌸' },
    { target: 'SONNE', pool: ['SONNE', 'SAND', 'SACK', 'SIEG'], emoji: '☀️' },
    { target: 'MOND', pool: ['MOND', 'MAUS', 'MEER', 'MAIS'], emoji: '🌙' },
    { target: 'STERN', pool: ['STERN', 'STEIN', 'STALL', 'STOCK'], emoji: '⭐' },
    { target: 'VOGEL', pool: ['VOGEL', 'VATER', 'VASE', 'VIEH'], emoji: '🐦' },
    { target: 'FISCH', pool: ['FISCH', 'FUSS', 'FELD', 'FEIER'], emoji: '🐟' },
    { target: 'APFEL', pool: ['APFEL', 'AMPEL', 'AMEISE', 'ACHT'], emoji: '🍎' },
    { target: 'BIRNE', pool: ['BIRNE', 'BROT', 'BURG', 'BANK'], emoji: '🍐' },
    { target: 'REGEN', pool: ['REGEN', 'RAD', 'REH', 'RING'], emoji: '🌧️' },
    { target: 'SCHNEE', pool: ['SCHNEE', 'SCHUH', 'SCHIFF', 'SCHAL'], emoji: '❄️' },
    { target: 'WOLKE', pool: ['WOLKE', 'WAND', 'WALD', 'WASSER'], emoji: '☁️' },
    { target: 'FEUER', pool: ['FEUER', 'FASS', 'FOTO', 'FUSS'], emoji: '🔥' },
    { target: 'WASSER', pool: ['WASSER', 'WALE', 'WOLF', 'WIND'], emoji: '💧' },
    { target: 'ERDE', pool: ['ERDE', 'ESEL', 'ENTE', 'EI'], emoji: '🌍' },
    { target: 'LUFT', pool: ['LUFT', 'LÖWE', 'LAMPE', 'LAUB'], emoji: '🌬️' },
    { target: 'BROT', pool: ['BROT', 'BALL', 'BÄR', 'BURG'], emoji: '🍞' },
    { target: 'MILCH', pool: ['MILCH', 'MAUS', 'MOND', 'MEER'], emoji: '🥛' },
    { target: 'KÄSE', pool: ['KÄSE', 'KUH', 'KATZE', 'KERN'], emoji: '🧀' },
    { target: 'APFEL', pool: ['APFEL', 'AMEISE', 'AST', 'ARM'], emoji: '🍎' },
    { target: 'BIRNE', pool: ['BIRNE', 'BUS', 'BAUM', 'BETT'], emoji: '🍐' },
    { target: 'BANANE', pool: ['BANANE', 'BOOT', 'BOCK', 'BLAU'], emoji: '🍌' },
    { target: 'EI', pool: ['EI', 'EULE', 'EIS', 'EIMER'], emoji: '🥚' },
    { target: 'FISCH', pool: ['FISCH', 'FEDER', 'FASS', 'FELD'], emoji: '🐟' },
    { target: 'FLEISCH', pool: ['FLEISCH', 'FLUSS', 'FORM', 'FUSS'], emoji: '🥩' },
    { target: 'GEMÜSE', pool: ['GEMÜSE', 'GANS', 'GLAS', 'GUT'], emoji: '🥦' },
    { target: 'OBST', pool: ['OBST', 'OFEN', 'OHR', 'ORT'], emoji: '🍎' },
    { target: 'SAFT', pool: ['SAFT', 'SONNE', 'SEE', 'SIEG'], emoji: '🧃' },
    { target: 'TEE', pool: ['TEE', 'TISCH', 'TAG', 'TIER'], emoji: '☕' },
    { target: 'KAFFEE', pool: ['KAFFEE', 'KUH', 'KERN', 'KIND'], emoji: '☕' },
    { target: 'SUPPE', pool: ['SUPPE', 'SAND', 'SACK', 'SIEG'], emoji: '🍲' },
    { target: 'SALAT', pool: ['SALAT', 'SONNE', 'SEE', 'SACK'], emoji: '🥗' },
    { target: 'PIZZA', pool: ['PIZZA', 'PUZZE', 'PONY', 'PARK'], emoji: '🍕' },
    { target: 'NUDELN', pool: ['NUDELN', 'NASE', 'NETZ', 'NUSS'], emoji: '🍝' },
    { target: 'REIS', pool: ['REIS', 'RAD', 'RING', 'REH'], emoji: '🍚' },
    { target: 'KARTOFFEL', pool: ['KARTOFFEL', 'KAMM', 'KIND', 'KUH'], emoji: '🥔' },
    { target: 'GURKE', pool: ['GURKE', 'GANS', 'GLAS', 'GEIST'], emoji: '🥒' },
    { target: 'TOMATE', pool: ['TOMATE', 'TISCH', 'TAG', 'TURM'], emoji: '🍅' },
    { target: 'ZWIEBEL', pool: ['ZWIEBEL', 'ZELT', 'ZUG', 'ZAHL'], emoji: '🧅' },
    { target: 'KNOBLAUCH', pool: ['KNOBLAUCH', 'KERN', 'KIND', 'KUSS'], emoji: '🧄' },
    { target: 'PFEFFER', pool: ['PFEFFER', 'PARK', 'PONY', 'PFAD'], emoji: '🌶️' },
    { target: 'SALZ', pool: ['SALZ', 'SONNE', 'SEE', 'SACK'], emoji: '🧂' },
    { target: 'ZUCKER', pool: ['ZUCKER', 'ZUG', 'ZAHL', 'ZEHN'], emoji: '🍭' },
    { target: 'HONIG', pool: ['HONIG', 'HASE', 'HAUS', 'HAND'], emoji: '🍯' },
    { target: 'MARMELADE', pool: ['MARMELADE', 'MAUS', 'MOND', 'MEER'], emoji: '🍓' },
    { target: 'SCHOKOLADE', pool: ['SCHOKOLADE', 'SCHUH', 'SCHIFF', 'SCHNEE'], emoji: '🍫' },
    { target: 'EIS', pool: ['EIS', 'EULE', 'ENTE', 'ERDE'], emoji: '🍦' },
    { target: 'KUCHEN', pool: ['KUCHEN', 'KUH', 'KATZE', 'KERN'], emoji: '🍰' },
    { target: 'KEKS', pool: ['KEKS', 'KUSS', 'KAMM', 'KOHL'], emoji: '🍪' },
    { target: 'GUMMIBÄR', pool: ['GUMMIBÄR', 'GANS', 'GLAS', 'GUT'], emoji: '🧸' },
    { target: 'BONBON', pool: ['BONBON', 'BOOT', 'BOCK', 'BURG'], emoji: '🍬' },
    { target: 'LUTSCHER', pool: ['LUTSCHER', 'LUFT', 'LÖWE', 'LAMPE'], emoji: '🍭' }
];

