export const elsaAnnaSentences: string[] = [
    "Elsa baut ein großes Schloss aus glitzerndem Eis.",
    "Anna findet eine kleine Blume im tiefen Schnee.",
    "Olaf tanzt fröhlich in der warmen Mittagssonne.",
    "Elsa zaubert bunte Eiskristalle an die hohen Fenster.",
    "Anna und Elsa spielen zusammen Fangen im Schlosshof.",
    "Kristoff bringt frisches Eis vom kalten Berg.",
    "Sven rennt schnell über die weiße Wiese.",
    "Elsa trägt ihr schönes Kleid in hellblau.",
    "Anna backt einen leckeren Schokokuchen für ihre Schwester.",
    "Olaf träumt von einem heißen Sommer am Meer.",
    "Elsa singt ein schönes Lied im hohen Norden.",
    "Anna reitet auf Sven durch den dunklen Wald.",
    "Kristoff hilft Elsa bei der Suche nach ihrem Buch.",
    "Olaf baut einen kleinen Freund aus weichem Schnee.",
    "Elsa verzaubert den ganzen See in glattes Eis.",
    "Anna trägt ihren warmen Mantel und rote Stiefel.",
    "Sven isst eine knackige Karotte aus Annas Hand.",
    "Elsa und Anna schauen die hellen Sterne an.",
    "Olaf hat eine kleine Nase aus einer Karotte.",
    "Kristoff fährt mit seinem Schlitten über den Hügel.",
    "Elsa malt ein Bild von ihrer geliebten Schwester.",
    "Anna lacht laut über Olafs lustige Witze.",
    "Sven schläft gemütlich im weichen Stroh im Stall.",
    "Elsa zaubert eine große Rutsche aus kühlem Eis.",
    "Anna findet eine geheime Kammer im alten Schloss.",
    "Olaf spielt Verstecken hinter den dicken Bäumen.",
    "Kristoff repariert seinen alten Schlitten für die Reise.",
    "Elsa gibt Anna eine herzliche Umarmung am Abend.",
    "Anna tanzt im Ballsaal unter den Kronleuchtern.",
    "Sven und Olaf rennen um die Wette zur Brücke.",
    "Elsa lässt es im kleinen Dorf sanft schneien.",
    "Anna pflückt bunte Beeren für ein süßes Frühstück.",
    "Kristoff erzählt spannende Geschichten am warmen Feuer.",
    "Olaf bekommt einen kleinen Regenschirm gegen die Sonne.",
    "Elsa öffnet die großen Tore für alle Besucher.",
    "Anna trägt eine glänzende Krone auf ihrem Kopf.",
    "Sven findet den Weg nach Hause im Nebel.",
    "Elsa zaubert glitzernden Schmuck für Annas Kleid.",
    "Anna und Elsa fahren gemeinsam Schlitten im Schnee.",
    "Olaf bewundert die bunten Blumen im Schlossgarten.",
    "Kristoff bringt Anna einen Becher mit heißem Kakao.",
    "Elsa macht für Olaf eine ewige kleine Schneewolke.",
    "Anna findet eine alte Karte im staubigen Regal.",
    "Sven springt mutig über den schmalen Bach.",
    "Elsa wandelt einen Regentropfen in einen Diamanten um.",
    "Anna verliert ihren Handschuh im tiefen Wald.",
    "Olaf singt ein Lied über seine vielen Freunde.",
    "Kristoff zeigt Anna den Weg zu den Trollen.",
    "Elsa lächelt, als sie den ersten Schnee sieht.",
    "Anna liest ein Buch über ferne, warme Länder.",
    "Sven bekommt eine neue Glocke für sein Geschirr.",
    "Elsa zaubert einen funkelnden Weihnachtsbaum aus Eis.",
    "Anna bereitet ein großes Fest für Arendelle vor.",
    "Olaf hilft Elsa beim Schmücken der hohen Wände.",
    "Kristoff bringt einen großen Sack voller Geschenke.",
    "Elsa zaubert kleine Schlittschuhe für ihre Freunde.",
    "Anna läuft sicher über die glatte Eisbahn.",
    "Sven zieht den Schlitten voller bunter Pakete.",
    "Olaf freut sich über seinen neuen blauen Schal.",
    "Elsa singt ein Wiegenlied für ihre kleine Schwester.",
    "Anna findet ein altes Spielzeug auf dem Dachboden.",
    "Kristoff baut ein kleines Haus aus festem Holz.",
    "Olaf möchte ein Bild von allen Freunden malen.",
    "Elsa zaubert einen Regenbogen aus buntem Licht.",
    "Anna springt fröhlich in eine tiefe Schneewehe.",
    "Sven liebt es, wenn Kristoff ihn sanft bürstet.",
    "Elsa macht eine große Esskulptur von einem Bären.",
    "Anna verteilt warme Suppe an die hungrigen Leute.",
    "Olaf beobachtet eine kleine Biene auf einer Blume.",
    "Kristoff trägt Anna über den tiefen Matsch.",
    "Elsa schließt die Augen und spürt den Wind.",
    "Anna bastelt eine Kette aus kleinen Muscheln.",
    "Sven schnaubt zufrieden in der kalten Bergluft.",
    "Elsa zaubert einen Thron aus blauem Kristall.",
    "Anna spielt auf der Flöte eine helle Melodie.",
    "Olaf versucht, einen Schmetterling vorsichtig zu fangen.",
    "Kristoff poliert seine Stiefel für den Ball.",
    "Elsa lässt kleine Eissplitter wie Sterne tanzen.",
    "Anna versteckt eine Überraschung unter dem Bett.",
    "Sven findet eine geheime Höhle im Gebirge.",
    "Elsa hilft Anna beim Flechten ihrer Haare.",
    "Anna zeichnet ein Porträt von Kristoff und Sven.",
    "Olaf rutscht den eisigen Berg schnell hinunter.",
    "Kristoff schenkt Anna einen Ring aus klarem Eis.",
    "Elsa baut eine Brücke über den weiten Fluss.",
    "Anna entdeckt einen alten Brief ihrer Eltern.",
    "Sven wartet geduldig vor der schweren Schlosstür.",
    "Elsa zaubert eine Krone für die kleine Anna.",
    "Anna und Olaf bauen zusammen ein Lebkuchenhaus.",
    "Olaf wundert sich über die gelbe Zitrone.",
    "Kristoff singt ein Duett mit seinem Freund Sven.",
    "Elsa bringt den Winter in das ferne Nachbarland.",
    "Anna trägt ein neues Kleid mit vielen Blumen.",
    "Sven freut sich über die erste grüne Wiese.",
    "Elsa zaubert einen Eisvogel, der leise zwitschert.",
    "Anna macht eine Schneeballschlacht mit Kristoff.",
    "Olaf hält die Hand von Elsa ganz fest.",
    "Kristoff findet eine goldene Münze im Flusssand.",
    "Elsa schaut aus dem Fenster auf ihr Reich.",
    "Anna wünscht allen eine gute und ruhige Nacht."
];
