// Lola Style sentences (100+)
export const lolaSentences: string[] = [
    // Ich + Verb
    'Ich bin da.', 'Ich bin hier.', 'Ich habe ein Buch.', 'Ich habe einen Ball.',
    'Ich gehe nach Hause.', 'Ich komme nach Hause.', 'Ich sehe dich.', 'Ich höre dich.',
    'Ich mache das.', 'Ich spiele gern.', 'Ich lerne Deutsch.', 'Ich lese ein Buch.',
    'Ich schreibe.', 'Ich male ein Bild.', 'Ich esse einen Apfel.', 'Ich trinke Wasser.',
    'Ich schlafe jetzt.', 'Ich lache laut.', 'Ich weine nicht.', 'Ich renne schnell.',
    'Ich tanze gern.', 'Du singst schön.', 'Er lacht viel.', 'Sie ist lieb.',
    'Es ist warm.', 'Wir sind hier.', 'Ihr spielt Ball.', 'Sie lesen Bücher.',

    // Familie
    'Das ist meine Mama.', 'Das ist mein Papa.', 'Das ist meine Oma.', 'Das ist mein Opa.',
    'Ich liebe meine Mama.', 'Ich sehe meinen Papa.', 'Meine Mama kommt.', 'Mein Papa arbeitet.',
    'Meine Oma liest.', 'Mein Opa schläft.', 'Meine Schwester spielt.', 'Mein Bruder lacht.',

    // Schule
    'Ich gehe in die Schule.', 'Ich lerne in der Schule.', 'Ich schreibe im Heft.',
    'Ich lese im Buch.', 'Das ist mein Lehrer.', 'Das ist meine Lehrerin.',
    'Ich sitze am Tisch.', 'Ich habe einen Platz.', 'Ich mache die Aufgabe.', 'Ich höre zu.',
    'Das ist mein Stift.', 'Das ist dein Heft.', 'Ich male eine Blume.',

    // Haus
    'Ich bin zu Hause.', 'Ich komme nach Hause.', 'Ich gehe ins Zimmer.', 'Ich öffne die Tür.',
    'Ich mache die Tür zu.', 'Ich sitze auf dem Stuhl.', 'Ich liege im Bett.',
    'Ich spiele im Zimmer.', 'Ich helfe zu Hause.', 'Ich räume auf.',
    'Mein Haus ist rot.', 'Die Tür ist blau.', 'Das Fenster ist groß.',

    // Вещи
    'Das ist mein Ball.', 'Das ist mein Buch.', 'Das ist mein Heft.', 'Ich habe eine Tasche.',
    'Ich nehme den Ball.', 'Ich lege das buch.', 'Ich sehe mein Spiel.', 'Ich finde mein Heft.',
    'Deine Tasche ist lila.', 'Hier ist dein Buch.', 'Wo ist meine Tasche?',

    // Еда
    'Ich esse ein Brot.', 'Ich esse einen Apfel.', 'Ich esse eine Banane.', 'Ich trinke Wasser.',
    'Ich trinke Saft.', 'Ich mag Brot.', 'Ich mag Apfel.', 'Ich will Wasser.',
    'Ich will essen.', 'Ich habe Hunger.', 'Ich esse Bananen.', 'Du trinkst Milch.',
    'Schokolade ist gut.', 'Ein Apfel ist gesund.',

    // Животные
    'Das ist ein Hund.', 'Das ist eine Katze.', 'Ich sehe einen Vogel.', 'Ich habe einen Fisch.',
    'Der Hund läuft.', 'Die Katze schläft.', 'Der Vogel fliegt.', 'Der Fisch schwimmt.',
    'Der Hund bellt laut.', 'Die Katze miaut.', 'Ein Vogel singt.',

    // Действия / команды
    'Komm mit!', 'Spiel mit!', 'Mach mit!', 'Hör zu!', 'Sieh mal!', 'Pass auf!',
    'Lauf schnell!', 'Geh langsam!', 'Bleib hier!', 'Warte kurz!',
    'Komm bitte her.', 'Geh bitte weg.', 'Sitz bitte still.',

    // Вежливость
    'Guten Tag!', 'Gute Nacht!', 'Danke schön!', 'Bitte schön!', 'Vielen Dank!',
    'Nein, danke.', 'Ja, gern.', 'Bitte sehr.', 'Danke für das Buch.',

    // Простые конструкции
    'Das ist gut.', 'Das ist schön.', 'Das ist groß.', 'Das ist klein.',
    'Das ist neu.', 'Das ist alt.', 'Das ist rot.', 'Das ist blau.',
    'Der Baum ist grün.', 'Die Sonne scheint.', 'Das Auto fährt.',

    // Вопросы
    'Wie heißt du?', 'Wer bist du?', 'Wo bist du?', 'Was machst du?', 'Kommst du mit?',
    'Hast du das?', 'Willst du das?', 'Kannst du das?',

    // Эмоции
    'Ich bin froh.', 'Ich bin müde.', 'Ich bin krank.', 'Ich bin traurig.',
    'Ich bin glücklich.', 'Ich habe Angst.', 'Ich bin lieb.'
];

// Lola Level 2 sentences (100)
export const lolaSentencesLvl2: string[] = [
    'Der große Hund läuft schnell im Park.',
    'Ich sehe einen kleinen Vogel auf dem Baum.',
    'Meine Mama kocht heute eine leckere Suppe.',
    'Mein Papa liest am Abend eine Zeitung.',
    'Wir spielen zusammen mit dem neuen Ball.',
    'Das kleine Kind schläft in seinem Bett.',
    'Ich habe ein schönes Geschenk für dich.',
    'Die Sonne scheint hell am blauen Himmel.',
    'Der Apfel auf dem Tisch ist rot und rund.',
    'Ich gehe gern mit meiner Freundin spazieren.',
    'In der Schule lernen wir viele neue Wörter.',
    'Mein Bruder hat heute eine schwere Tasche.',
    'Wo hast du mein blaues Auto versteckt?',
    'Ich möchte heute einen kalten Saft trinken.',
    'Das gelbe Haus hat ein rotes Dach.',
    'Der Elefant im Zoo ist sehr groß und grau.',
    'Meine Katze mag es, wenn ich sie streichle.',
    'Wir essen heute Pizza zum Abendessen.',
    'Kannst du mir bitte beim Malen helfen?',
    'Heute ist ein schöner Tag zum Spielen.',
    'Ich schreibe einen langen Brief an meine Oma.',
    'Der grüne Frosch springt in den kleinen Teich.',
    'Mein Opa erzählt mir oft spannende Geschichten.',
    'Wir gehen am Wochenende in den großen Wald.',
    'Ich habe meine Hausaufgaben schon fertig gemacht.',
    'Der Bäcker backt heute frisches, warmes Brot.',
    'Die Kinder laufen fröhlich über die Wiese.',
    'Das Kleid steht dir wirklich sehr gut.',
    'Ich habe ein neues Fahrrad zum Geburtstag bekommen.',
    'Der Zug kommt um acht Uhr am Bahnhof an.',
    'Wir müssen heute unser Zimmer ordentlich aufräumen.',
    'Das Wasser im See ist heute sehr kalt.',
    'Ich finde meinen Bleistift in der Tasche nicht.',
    'Meine Schwester spielt wunderbar auf der Flöte.',
    'Der Löwe ist der König der vielen Tiere.',
    'Wir besuchen morgen meine Tante in der Stadt.',
    'Ich esse am liebsten Nudeln mit Tomatensoße.',
    'Das Buch über Dinosaurier ist sehr interessant.',
    'Der Wind weht heute besonders stark draußen.',
    'Ich putze mir jeden Morgen die Zähne.',
    'Die Blumen im Garten blühen jetzt wunderschön.',
    'Mein Freund wohnt in einem sehr hohen Haus.',
    'Wir hören dem Lehrer aufmerksam zu.',
    'Der bunte Schmetterling fliegt von Blume zu Blume.',
    'Ich habe zwei kleine Hamster in meinem Käfig.',
    'Das Auto von meinem Onkel ist sehr schnell.',
    'Heute Abend schauen wir einen lustigen Film.',
    'Ich trage heute meine warme Jacke und Mütze.',
    'Der Schnee im Winter ist weiß und weich.',
    'Ich möchte später einmal Pilot werden.',
    'Die Schule fängt jeden Morgen pünktlich an.',
    'Mein Hund kann schon Männchen machen.',
    'Wir trinken Tee, wenn es draußen regnet.',
    'Der Regenbogen hat viele verschiedene Farben.',
    'Ich male ein Bild von meiner ganzen Familie.',
    'Der Postbote bringt heute ein großes Paket.',
    'Wir laufen um die Wette bis zum Baum.',
    'Mein neuer Rucksack ist blau und sehr stabil.',
    'Die Maus versteckt sich vor der Katze.',
    'Ich esse jeden Tag einen frischen Apfel.',
    'Mein Teddybär schläft immer in meinem Arm.',
    'Wir gehen heute Nachmittag auf den Spielplatz.',
    'Die Glocke läutet und die Pause beginnt.',
    'Ich kann schon bis hundert zählen.',
    'Der Marienkäfer hat sieben schwarze Punkte.',
    'Ich helfe meiner Mutter beim Tischdecken.',
    'Das Flugzeug fliegt hoch über den Wolken.',
    'Wir haben im Winter eine große Schneeballschlacht.',
    'Der Igel sucht sich ein Bett aus Blättern.',
    'Ich mag es, wenn wir zusammen Lieder singen.',
    'Der Affe frisst eine gelbe, krumme Banane.',
    'Die Tür geht auf und der Gast kommt rein.',
    'Ich habe mein Pausenbrot in der Schule vergessen.',
    'Das kleine Pony reitet über das grüne Feld.',
    'Wir bauen im Winter einen großen Schneemann.',
    'Mein Vater repariert heute das kaputte Fahrrad.',
    'Die Enten schwimmen ruhig auf dem Teich.',
    'Ich lese jeden Abend eine Geschichte im Bett.',
    'Das Eichhörnchen sammelt Nüsse für den Winter.',
    'Wir machen heute einen Ausflug zum Bauernhof.',
    'Der Kaugummi klebt unter dem hölzernen Tisch.',
    'Ich habe ein neues Rätselbuch geschenkt bekommen.',
    'Die Sterne leuchten in der dunklen Nacht.',
    'Wir pflanzen heute eine kleine Blume ein.',
    'Mein Lieblingsfach in der Schule ist Sport.',
    'Die Giraffe hat einen sehr langen Hals.',
    'Ich trinke morgens immer ein Glas Milch.',
    'Der Wecker klingelt und ich muss aufstehen.',
    'Wir basteln heute eine bunte Laterne.',
    'Der Zauberer zeigt uns einen tollen Trick.',
    'Ich habe mir beim Hinfallen das Knie verletzt.',
    'Wir klettern gern auf den großen Kletterbaum.',
    'Der Polizist regelt den Verkehr auf der Straße.',
    'Ich freue mich schon sehr auf die Ferien.',
    'Der Fischer fängt einen dicken, großen Fisch.',
    'Wir malen bunte Bilder an die Fenster.',
    'Das kleine Lamm springt über den Zaun.',
    'Ich kann schon meinen Namen richtig schreiben.',
    'Die Feuerwehr löscht das Feuer im Haus.',
    'Heute feiern wir eine tolle Geburtstagsparty.'
];

// Lola Level 3 stories (20) - 5 sentences each
export const lolaStoriesLvl3: string[] = [
    'Der kleine Igel sucht Futter. Er findet einen großen Apfel. Der Apfel schmeckt sehr süß. Jetzt ist der Igel satt. Er schläft unter einem Baum.',
    'Heute ist ein sonniger Tag. Wir gehen in den Park. Ich habe meinen bunten Ball. Wir spielen zusammen auf der Wiese. Das macht uns viel Spaß.',
    'Meine Katze heißt Minka. Sie hat ein weiches Fell. Minka spielt gern mit Wolle. Am Abend schläft sie gern. Ich habe meine Katze lieb.',
    'Wir bauen einen hohen Turm. Die Steine sind bunt. Der Turm wackelt ein bisschen. Oh weh, er fällt um! Wir bauen ihn einfach neu.',
    'In der Schule lernen wir. Ich schreibe in mein Heft. Die Lehrerin liest uns vor. Wir hören alle gespannt zu. Lernen macht mir große Freude.',
    'Der Hund bellt laut. Er sieht eine kleine Maus. Die Maus rennt schnell weg. Der Hund läuft hinterher. Aber die Maus ist schneller.',
    'Ich backe mit meiner Mama. Wir machen einen Schokokuchen. Der Teig riecht sehr gut. Jetzt kommt er in den Ofen. Wir freuen uns auf den Kuchen.',
    'Mein Fahrrad ist blau. Ich fahre auf dem Weg. Der Wind weht im Gesicht. Ich trage einen gelben Helm. Radfahren ist mein liebstes Hobby.',
    'Im Garten blühen bunte Blumen. Ich gieße sie mit Wasser. Ein Schmetterling fliegt vorbei. Er setzt sich auf eine rose. Die Natur ist wirklich schön.',
    'Der Winter ist endlich da. Es fällt viel weißer Schnee. Wir bauen einen großen Schneemann. Er hat eine dicke Nase. Wir tragen warme Mützen.',
    'Mein kleiner Bruder spielt gern. Er hat viele bunte Autos. Wir fahren ein schnelles Rennen. Sein Auto gewinnt dieses Mal. Wir lachen beide sehr laut.',
    'Wir gehen heute in den Zoo. Dort sehen wir viele Tiere. Der Elefant hat einen Rüssel. Die Affen klettern sehr hoch. Es ist ein toller Ausflug.',
    'Ich habe ein neues Buch. Die Bilder darin sind bunt. Ich lese die erste Seite. Die Geschichte ist sehr spannend. Lesen ist wie ein Abenteuer.',
    'Der Regen trommelt am Fenster. Wir bleiben heute im Haus. Ich male ein schönes Bild. Mein Bild hat viele Farben. Draußen wird alles richtig nass.',
    'Mein Opa hat einen Garten. Dort wachsen Äpfel und Birnen. Wir pflücken das reife Obst. Es schmeckt frisch gepflückt am besten. Wir helfen Opa sehr gern.',
    'Die Sonne geht langsam unter. Der Himmel wird ganz rot. Die Vögel fliegen zum Nest. Es wird nun langsam dunkel. Wir gehen jetzt nach Hause.',
    'Ich habe einen grünen Drachen. Er fliegt hoch im Wind. Ich halte die Schnur fest. Der Drache tanzt in den Wolken. Das sieht sehr lustig aus.',
    'Wir feiern heute ein Fest. Es gibt Musik und Tanz. Alle meine Freunde sind da. Wir essen leckeres Eis. Es ist ein schöner Tag.',
    'Das Meer ist sehr blau. Wir spielen im warmen Sand. Ich suche kleine, weiße Muscheln. Eine Welle kommt zur Küste. Das Wasser ist angenehm kühl.',
    'Mein Teddy heißt Brummi. Er begleitet mich überall hin. Nachts bewacht er mein Bett. Brummi ist mein bester Freund. Ich kuschele gern mit ihm.',
    'Heute gehen wir einkaufen. Mama braucht frisches Gemüse. Ich darf mir Obst aussuchen. Wir kaufen einen roten Apfel. Das Einkaufen macht mir Spaß.',
    'Die Sonne scheint hell. Wir gehen zum See. Das Wasser ist sehr blau. Ich springe mutig hinein. Es spritzt überall hin.',
    'Mein Zimmer ist unordentlich. Überall liegen bunte Bausteine. Ich räume alles auf. Jetzt ist es wieder sauber. Ich fühle mich sehr wohl.',
    'Ein kleiner Vogel singt. Er sitzt ganz oben. Das Lied klingt sehr schön. Ich höre ihm leise zu. Dann fliegt er weit weg.',
    'Wir malen ein Plakat. Es hat viele Farben. Wir benutzen bunte Stifte. Die Lehrerin lobt uns. Wir hängen es auf.',
    'Der Mond leuchtet hell. Es ist jetzt Nacht. Alle Lichter gehen aus. Ich kuschele mich ein. Ich träume etwas Schönes.',
    'Mein Bruder hat Geburtstag. Wir backen einen Kuchen. Es gibt viele Geschenke. Er freut sich sehr. Gemeinsam singen wir laut.',
    'Der Herbst ist kühl. Die Blätter sind bunt. Wir sammeln viele Kastanien. Wir basteln kleine Männchen. Das macht richtig Spaß.',
    'Ich habe einen Ball. Der Ball ist rot. Wir spielen im Park. Mein Freund fängt ihn. Wir lachen dabei viel.',
    'Eine Spinne baut. Das Web ist groß. Es glänzt im Licht. Die Spinne wartet geduldig. Die Fliege fliegt vorbei.',
    'Wir gehen spazieren. Der Wald ist grün. Wir sehen ein Reh. Es springt schnell weg. Die Stille ist schön.',
    'Mein Hund heißt Bello. Er hat braunes Fell. Wir gehen oft raus. Er rennt dem Ball nach. Bello ist mein Freund.',
    'Ich lese ein Buch. Die Geschichte ist spannend. Es geht um Piraten. Die Schatzsuche beginnt jetzt. Ich lese immer weiter.',
    'Die Schule macht Spaß. Wir rechnen heute Aufgaben. Mathe ist mein Lieblingsfach. Ich habe alles richtig. Ich bin sehr stolz.',
    'Der Schnee ist weich. Wir bauen eine Burg. Sie ist sehr hoch. Wir verstecken uns darin. Der Winter ist toll.',
    'Meine Oma kocht gut. Es gibt heute Nudeln. Die Soße schmeckt lecker. Ich esse alles auf. Danke für das Essen.',
    'Ein Regenwurm ist lang. Er kriecht im Garten. Er mag feuchte Erde. Ich beobachte ihn genau. Dann verschwindet er wieder.',
    'Wir haben ein Pferd. Es heißt kleiner Stern. Ich darf es bürsten. Das Fell glänzt schön. Wir reiten über Wiesen.',
    'Die Bienen fliegen fleißig. Sie sammeln klebrigen Pollen. Die Blumen duften herrlich. Der Honig wird lecker. Die Natur arbeitet hart.',
    'Mein Drachen fliegt hoch. Er hat einen Schwanz. Der Wind weht kräftig. Ich halte ihn fest. Es sieht toll aus.',
    'Wir besuchen ein Museum. Dort gibt es Knochen. Ein Dino war riesig. Ich lerne viel Neues. Es war sehr interessant.',
    'Die Ameisen laufen schnell. Sie tragen kleine Blätter. Sie arbeiten alle zusammen. Ihr Bau ist groß. Ameisen sind sehr stark.',
    'Ich male ein Schiff. Es hat weiße Segel. Das Meer ist blau. Die Wellen sind hoch. Mein Bild ist schön.',
    'Wir spielen heute Verstecken. Ich suche ein Versteck. Ich bin ganz leise. Niemand findet mich hier. Das Spiel ist lustig.',
    'Der Zirkus ist da. Wir sehen viele Akrobaten. Der Clown macht Witze. Alle Kinder lachen laut. Die Show ist prima.',
    'Mein Freund heißt Max. Wir spielen oft Lego. Wir bauen eine Station. Sie hat viele Details. Zusammen ist es besser.',
    'Die Erdbeeren sind reif. Wir pflücken sie im Garten. Sie sind rot und süß. Wir machen daraus Marmelade. Das schmeckt sehr gut.',
    'Ein Frosch quakt laut. Er sitzt am Teich. Seine Haut ist grün. Er springt ins Wasser. Der Teich ist ruhig.',
    'Wir machen ein Picknick. Es gibt frisches Brot. Wir sitzen auf der Decke. Die Sonne wärmt uns. Ein schöner Nachmittag heute.',
    'Mein Wecker klingelt früh. Ich stehe langsam auf. Die Sonne geht auf. Ein neuer Tag beginnt. Ich freue mich darauf.'
];

// Lola Level 4 stories (100) - 5 sentences each
export const lolaStoriesLvl4: string[] = [
    'Der kleine Hamster Goldi hamstert Körner. Er füllt seine Backen ganz voll. In seinem Häuschen leert er sie aus. Jetzt hat er einen großen Vorrat. Goldi ist ein fleißiges Tier.',
    'Die Schildkröte Susi läuft sehr langsam. Sie trägt ihr hartes Haus auf dem Rücken. Wenn sie Angst hat, zieht sie den Kopf ein. Susi frisst gern frischen Salat. Sie sonnt sich auf einem Stein.',
    'Der bunte Papagei kann sprechen. Er sagt laut: "Hallo, wie geht es dir?". Er hat grüne und rote Federn. Er fliegt im Käfig hin und her. Alle Kinder staunen über den Vogel.',
    'Das kleine Kätzchen spielt mit einer Feder. Es springt hoch in die Luft. Dann rollt es sich auf dem Teppich. Es schnurrt ganz leise vor Glück. Kätzchen sind sehr verspielt.',
    'Im Wald lebt ein brauner Bär. Er sucht nach süßem Honig. Die Bienen fliegen um ihn herum. Der Bär hat ein dickes Fell. Er schläft im Winter in einer Höhle.',
    'Ein kleiner Elefant spritzt mit Wasser. Er benutzt seinen Rüssel wie eine Dusche. Das macht ihm bei der Hitze Spaß. Seine Ohren wackeln hin und her. Er ist das größte Tier im Zoo.',
    'Die Giraffe hat einen sehr langen Hals. Sie frisst die Blätter oben am Baum. Niemand sonst kommt so hoch wie sie. Ihr Fell hat braune Flecken. Sie läuft elegant über die Wiese.',
    'Der Fuchs schleicht leise durch das Gebüsch. Er hat einen buschigen, roten Schwanz. Seine Augen leuchten in der Nacht. Er sucht nach einer kleinen Maus. Der Fuchs ist sehr schlau.',
    'Im Teich schwimmt ein goldener Fisch. Seine Schuppen glänzen im Sonnenlicht. Er macht kleine Blasen im Wasser. Er versteckt sich unter einem Blatt. Das Wasser ist ganz ruhig.',
    'Der Pinguin watschelt über das kalte Eis. Er trägt einen schwarz-weißen Frack. Im Wasser schwimmt er sehr schnell. Er springt mutig in die Wellen. Pinguine lieben den kalten Winter.',
    'Ein kleiner Marienkäfer sitzt auf meiner Hand. Er hat sechs Beine und viele Punkte. Vorsichtig krabbelt er an meinem Finger. Dann breitet er seine Flügel aus. Er fliegt hoch in den Himmel.',
    'Der Hase hoppelt schnell über das Feld. Er hat lange Ohren und eine Stupsnase. Er sucht nach einer saftigen Karotte. Wenn er etwas hört, bleibt er stehen. Hasen können sehr gut hören.',
    'Die Spinne webt ein kunstvolles Netz. Es glänzt im Morgentau wie Diamanten. Die Spinne wartet in der Mitte. Sie ist eine geduldige Jägerin. Insekten fliegen in das klebrige Netz.',
    'Eine kleine Maus knabbert am Käse. Sie macht ganz leise Geräusche. Plötzlich hört sie ein Geräusch. Schnell rennt sie in ihr Loch. Dort ist sie sicher vor der Katze.',
    'Der Wolf heult laut im Mondschein. Seine Freunde antworten ihm aus der Ferne. Das klingt ein bisschen unheimlich. Wölfe leben zusammen in einem Rudel. Sie sind sehr starke Tiere.',
    'Im Stall wiehert das weiße Pferd. Es wartet auf seinen Hafer. Ich bürste sein glänzendes Fell. Das Pferd schüttelt seine lange Mähne. Es freut sich auf unseren Ausritt.',
    'Die Biene summt von Blume zu Blume. Sie sammelt gelben Blütenstaub. Daraus machen die Bienen süßen Honig. Die Königin wohnt im Bienenstock. Bienen sind sehr nützliche Tiere.',
    'Ein kleiner Igel rollt sich zusammen. Er zeigt seine vielen spitzen Stacheln. So schützt er sich vor Gefahren. Er sucht unter Blättern nach Futter. Im Winter hält er Winterschlaf.',
    'Das Schaf hat eine dicke, weiße Wolle. Es frisst das grüne Gras auf der Weide. Das kleine Lamm springt fröhlich herum. Der Hirte passt gut auf die Herde auf. Schafe sind friedliche Tiere.',
    'Im Zoo sehen wir einen Tiger. Er hat schwarze Streifen im Fell. Seine Tatzen sind sehr groß. Er gähnt und zeigt seine Zähne. Der Tiger ist eine wilde Raubkatze.',
    'In der Schule schreiben wir heute ein Diktat. Ich spitze meinen Bleistift ganz vorsichtig. Ich konzentriere mich auf jedes Wort. Der Lehrer schreibt an die Tafel. Ich habe keine Fehler gemacht.',
    'In der Pause spielen wir Fangen. Wir rennen über den großen Schulhof. Alle Kinder lachen und rufen laut. Die Glocke läutet das Ende ein. Wir gehen ordentlich zurück ins Klassenzimmer.',
    'In Kunst malen wir mit Wasserfarben. Ich mische Blau und Gelb zu Grün. Mein Bild zeigt eine bunte Blumenwiese. Die Farben trocknen langsam auf dem Papier. Malen macht mir sehr viel Spaß.',
    'Im Sportunterricht turnen wir heute. Wir klettern an der hohen Sprossenwand. Ich schaffe es bis ganz nach oben. Das erfordert viel Kraft und Mut. Wir machen auch eine Purzelbaum.',
    'In der Bibliothek leihe ich ein Buch aus. Es geht um Sterne und Planeten. Ich lese es heute Abend im Bett. Das Buch hat viele tolle Fotos. Ich lerne viel über das Weltall.',
    'Wir rechnen heute schwierige Aufgaben. Plus und Minus sind für mich einfach. Der Lehrer lobt meine saubere Schrift. Ich helfe meinem Nachbarn bei einer Aufgabe. Mathe ist mein Lieblingsfach.',
    'In Sachkunde lernen wir über Bäume. Wir sammeln bunte Blätter im Wald. Ich weiß jetzt, wie eine Eiche aussieht. Wir kleben die Blätter in unser Heft. Die Natur ist sehr interessant.',
    'Im Musikraum singen wir ein neues Lied. Der Lehrer spielt dazu auf dem Klavier. Unsere Stimmen klingen zusammen sehr schön. Wir klatschen im Rhythmus der Musik. Singen macht gute Laune.',
    'Ich habe meine Hausaufgaben schon gemacht. Ich habe Sätze über den Sommer geschrieben. Meine Mutter kontrolliert meine Fehler. Morgen zeige ich das Heft dem Lehrer. Ich bin gut vorbereitet.',
    'Mein Schulranzen ist heute sehr schwer. Ich habe viele Bücher und Hefte dabei. Auch meine Brotdose ist gut gefüllt. Ich trage den Ranzen auf dem Rücken. Der Weg zur Schule ist kurz.',
    'In der Schule haben wir ein neues Aquarium. Es schwimmen bunte Fische darin. Wir dürfen die Fische jeden Tag füttern. Das Wasser muss immer sauber sein. Wir beobachten die Tiere gern.',
    'Heute machen wir ein gemeinsames Frühstück. Jeder bringt etwas Gesundes von zu Hause mit. Wir essen Äpfel, Brot und Käse. Zusammen schmeckt es uns viel besser. Wir unterhalten uns dabei nett.',
    'Wir basteln Laternen für das Fest. Wir benutzen buntes Papier und Kleber. Meine Laterne sieht aus wie eine Sonne. Wir freuen uns auf den Umzug am Abend. Das Licht leuchtet hell.',
    'Im Klassenraum stehen viele bunte Stühle. Wir sitzen an unseren großen Tischen. An der Wand hängen unsere Bilder. Wir halten unseren Raum immer sauber. Hier lernen wir jeden Tag.',
    'Ich habe eine neue Federmappe bekommen. Darin sind bunte Stifte und ein Lineal. Auch ein Radiergummi ist dabei. Ich ordne meine Stifte nach Farben. Alles ist nun griffbereit.',
    'Wir lernen heute ein neues Gedicht auswendig. Ich sage die Verse leise vor mich hin. Es geht um den bunten Herbstwind. Morgen sage ich es der Klasse vor. Ich bin ein bisschen aufgeregt.',
    'In der Schule gibt es eine große Pause. Wir bekommen frische Milch zum Trinken. Das stärkt uns für die nächsten Stunden. Wir spielen zusammen mit dem Seil. Die Zeit vergeht sehr schnell.',
    'Wir machen heute ein Experiment mit Wasser. Wir schauen, was schwimmt und was sinkt. Ein Stein sinkt sofort nach unten. Ein Blatt schwimmt oben auf. Das ist sehr spannend.',
    'Der Lehrer erzählt uns eine alte Sage. Es geht um Ritter und ein Schloss. Wir hören alle ganz aufmerksam zu. Ich stelle mir die Geschichte bildlich vor. Geschichten erzählen ist toll.',
    'Ich habe eine Eins in der Mathearbeit. Mein Vater freut sich sehr über die Note. Er schenkt mir ein kleines Spielzeug. Ich nehme mir vor, weiter fleißig zu lernen. Erfolg macht stolz.',
    'Am Wochenende besuchen wir meine Oma. Sie wohnt in einem kleinen Dorf. Wir backen zusammen einen leckeren Apfelkuchen. Der Duft zieht durch das ganze Haus. Oma erzählt mir alte Geschichten.',
    'Mein Papa repariert heute mein Fahrrad. Die Kette war locker und der Reifen platt. Jetzt glänzt das Rad wieder wie neu. Ich mache eine Probefahrt im Garten. Danke für die Hilfe, Papa!',
    'Meine kleine Schwester lernt gerade laufen. Sie macht ihre ersten vorsichtigen Schritte. Ich halte sie fest an der Hand. Sie lacht und freut sich sehr. Wir sind alle stolz auf sie.',
    'Wir räumen heute gemeinsam die Wohnung auf. Ich sortiere meine Spielsachen im Kinderzimmer. Meine Mutter staubsaugt den dicken Teppich. Danach ist alles wieder ordentlich und sauber. Ordnung muss sein.',
    'Abends lesen wir zusammen ein Buch. Ich darf mir eine Geschichte aussuchen. Mein Vater liest mit verstellter Stimme vor. Ich kuschele mich in meine Decke. Das ist mein liebstes Ritual.',
    'Wir kochen heute Nudeln mit Tomatensoße. Ich darf den Käse über das Essen streuen. Die Soße duftet nach frischen Kräutern. Wir decken gemeinsam den großen Tisch. Guten Appetit an alle!',
    'In unserem Garten blühen rote Rosen. Ich helfe meiner Mutter beim Gießen. Die Erde riecht nach dem frischen Wasser. Ein kleiner Vogel badet in einer Pfütze. Der Garten ist ein schöner Ort.',
    'Wir machen einen Ausflug in den Wald. Wir suchen nach Pilzen und Kastanien. Die Luft riecht nach Moos und Blättern. Wir hören das Klopfen eines Spechtes. Der Wald ist voller Wunder.',
    'Heute kommen meine Freunde zu Besuch. Wir spielen im Zimmer mit den Bausteinen. Wir bauen eine riesige Stadt mit Autos. Danach essen wir zusammen ein Eis. Es ist ein toller Nachmittag.',
    'Mein Opa hat eine große Werkstatt. Dort baut er schöne Dinge aus Holz. Er zeigt mir, wie man einen Nagel einschlägt. Ich darf ihm beim Sägen helfen. Ich lerne viel von meinem Opa.',
    'Wir feiern heute ein großes Familienfest. Alle meine Tanten und Onkel kommen. Es gibt viel Musik und gutes Essen. Wir tanzen zusammen im Wohnzimmer. Alle sind fröhlich und lachen.',
    'Ich habe ein eigenes Zimmer bekommen. Die Wände sind hellblau gestrichen. Mein Bett steht direkt am Fenster. Ich habe dort Platz für meine Spielsachen. Ich fühle mich hier sehr wohl.',
    'Wir schauen uns alte Fotos an. Ich sehe meine Eltern als Kinder. Sie sahen damals ganz anders aus. Wir lachen über die lustige Kleidung. Erinnerungen sind etwas Schönes.',
    'Meine Mutter näht mir ein Kostüm. Ich möchte an Karneval ein Tiger sein. Der Stoff ist weich und gestreift. Ich probiere das Kostüm heute an. Es passt mir ganz genau.',
    'Wir gehen heute zusammen einkaufen. Wir brauchen Milch, Eier und frisches Brot. Ich darf den kleinen Einkaufswagen schieben. Wir finden alles auf unserer Liste. Einkaufen ist wie eine Suche.',
    'Mein Bruder und ich spielen Fußball. Wir schießen Tore auf der Wiese. Manchmal gewinne ich, manchmal er. Das Wichtigste ist der gemeinsame Spaß. Wir sind ein gutes Team.',
    'Wir zünden eine Kerze am Abend an. Das Licht flackert warm und hell. Wir unterhalten uns über den Tag. Es ist gemütlich in unserem Haus. Wir genießen die gemeinsame Zeit.',
    'Ich helfe beim Decken des Tisches. Ich lege Messer, Gabel und Löffel bereit. Auch die bunten Servietten dürfen nicht fehlen. Alles sieht nun sehr einladend aus. Das Essen ist fast fertig.',
    'Wir waschen heute zusammen das Auto. Wir benutzen viel Schaum und Wasser. Die Seifenblasen fliegen in der Luft. Das Auto glänzt danach in der Sonne. Wir sind beide nass geworden.',
    'Meine Oma strickt mir warme Socken. Die Wolle ist bunt und sehr weich. Sie benutzt vier lange Stricknadeln. Die Socken halten meine Füße warm. Ich danke meiner Oma sehr.',
    'Die Sonne scheint hell am Himmel. Die Vögel zwitschern in den Bäumen. Ich gehe ohne Jacke nach draußen. Alles ist grün und voller Leben. Der Sommer ist endlich da.',
    'Der Regen prasselt gegen die Scheibe. Ich trage meine gelben Gummistiefel. Ich springe mutig in eine tiefe Pfütze. Das Wasser spritzt nach allen Seiten. Ich werde gar nicht nass.',
    'Der Wind bläst stark durch die Haare. Ich lasse meinen Drachen steigen. Er fliegt hoch über den Feldern. Ich muss die Schnur fest halten. Der Wind ist heute sehr kräftig.',
    'Der erste Schnee fällt leise nieder. Die Welt sieht aus wie gepudert. Wir bauen einen dicken Schneemann. Er bekommt eine Nase aus einer Karotte. Der Winter ist wunderschön.',
    'Im Herbst färben sich die Blätter. Sie leuchten in Rot, Gelb und Braun. Sie fallen langsam von den Bäumen. Ich sammle die schönsten Blätter ein. Der Wald ist nun bunt.',
    'Der Regenbogen hat viele Farben. Er erscheint nach einem kurzen Schauer. Er verbindet den Himmel mit der Erde. Ich versuche, das Ende zu finden. Ein Wunder der Natur.',
    'Die Sterne funkeln in der Nacht. Der Mond sieht aus wie eine Sichel. Es ist ganz still im Garten. Ich schaue aus meinem Fenster hoch. Das Weltall ist unendlich groß.',
    'Der Donner grollt laut in der Ferne. Ein Blitz zuckt hell am Himmel. Wir bleiben sicher im warmen Haus. Das Gewitter zieht schnell an uns vorbei. Die Natur zeigt ihre Kraft.',
    'Die Blumen duften herrlich auf der Wiese. Viele Bienen fliegen von Kelch zu Kelch. Ich pflücke einen bunten Strauß. Er steht jetzt in einer Vase. Der Frühling ist erwacht.',
    'Das Meer rauscht beruhigend am Strand. Die Wellen schlagen sanft an das Ufer. Ich sammle kleine, glatte Steine. Das Wasser ist angenehm und kühl. Ich liebe den Urlaub am Meer.',
    'Der Nebel liegt dicht über den Feldern. Man kann nicht sehr weit sehen. Alles wirkt geheimnisvoll und grau. Die Sonne kämpft sich langsam durch. Ein kühler Morgen bricht an.',
    'Im Wald suchen wir nach Tierspuren. Ich finde den Abdruck von einem Reh. Wir bewegen uns ganz leise. Das Moos ist weich wie ein Teppich. Wir entdecken viele kleine Geheimnisse.',
    'Die Sonne geht langsam unter. Der Himmel färbt sich orange und violett. Es wird nun kühler im Garten. Die ersten Grillen fangen an zu zirpen. Der Tag neigt sich dem Ende.',
    'Wir pflanzen einen kleinen Apfelbaum. Wir graben ein tiefes Loch in die Erde. Der Baum braucht viel Wasser und Licht. In ein paar Jahren ernten wir Äpfel. Wir pflegen den Baum gut.',
    'Der Bach plätschert über kleine Steine. Das Wasser ist klar und sehr kalt. Ich baue ein kleines Schiff aus Rinde. Es treibt schnell mit der Strömung. Der Bach führt zum großen See.',
    'Im Winter sind die Fenster gefroren. Es gibt dort wunderschöne Eisblumen. Ich male mit dem Finger ein Herz. Die Kälte beißt in meine Nase. Drinnen ist es warm und gemütlich.',
    'Wir beobachten die Ameisen im Garten. Sie tragen schwere Lasten zu ihrem Bau. Sie arbeiten alle fleißig zusammen. Der Ameisenhaufen ist sehr groß. Kleine Tiere mit großer Kraft.',
    'Ein Schmetterling setzt sich auf eine Blume. Seine Flügel sind blau und schwarz. Er saugt den süßen Nektar. Dann fliegt er leichtfüßig weiter. Die Natur ist voller Farben.',
    'Wir sammeln bunte Kastanien im Park. Wir basteln daraus kleine Männchen. Wir benutzen Streichhölzer für die Beine. Das ist eine tolle herbstliche Idee. Wir freuen uns über die Figuren.',
    'Der Mond leuchtet hell durch die Bäume. Er begleitet mich auf meinem Weg. Die Nacht ist friedlich und still. Ich träume von fernen Ländern. Gute Nacht an die ganze Welt.',
    'Ich lerne heute ein neues Instrument. Es ist eine kleine, hölzerne Flöte. Ich übe die ersten einfachen Töne. Meine Eltern hören mir aufmerksam zu. Musik zu machen ist wunderbar.',
    'Wir gehen heute ins Schwimmbad. Ich springe vom kleinen Brett ins Wasser. Ich kann schon ein bisschen schwimmen. Das Wasser spritzt mir in die Augen. Schwimmen ist mein liebstes Hobby.',
    'Ich baue ein Modell aus kleinen Steinen. Es wird ein großes, weißes Schloss. Ich brauche viel Geduld und Zeit. Am Ende steht das Schloss stolz da. Ich habe es ganz allein gebaut.',
    'Wir backen heute bunte Plätzchen. Wir stechen Sterne, Herzen und Monde aus. Der Teig schmeckt auch roh sehr gut. Danach verzieren wir sie mit Zucker. Die Küche duftet herrlich.',
    'Ich schreibe eine Geschichte über Drachen. Der Drache kann blaues Feuer spucken. Er rettet eine Prinzessin aus Not. Meine Fantasie kennt keine Grenzen. Schreiben ist wie eine Reise.',
    'Wir spielen heute ein Brettspiel. Ich würfele eine Sechs und ziehe vor. Mein Bruder hat leider kein Glück. Wir lachen zusammen über den Spielzug. Gewinnen ist nicht das Wichtigste.',
    'Ich sammle bunte Sticker in einem Album. Ich tausche doppelte Bilder mit Freunden. Mein Album ist schon fast voll. Ich ordne sie nach verschiedenen Themen. Das Sammeln macht mir Freude.',
    'Wir gehen heute auf den Spielplatz. Ich schaukele so hoch ich kann. Die Luft weht mir um die Nase. Danach rutsche ich die steile Bahn. Der Spielplatz ist ein Abenteuer.',
    'Ich mache heute ein Puzzle mit vielen Teilen. Ich suche zuerst die Randstücke heraus. Langsam entsteht ein buntes Bild. Es zeigt viele Tiere im Urwald. Ich habe das Puzzle geschafft.',
    'Wir basteln ein Schiff aus einem Karton. Wir benutzen Segel aus altem Stoff. Das Schiff heißt "Wilder Pirat". Wir lassen es in der Wanne schwimmen. Ahoi, kleine Kapitäne!',
    'Ich lerne heute einen Zaubertrick. Ich lasse eine Münze verschwinden. Meine Freunde schauen ganz genau hin. Sie wissen nicht, wie es geht. Ich bin ein kleiner Zauberer.',
    'Wir machen heute einen langen Spaziergang. Wir entdecken viele neue Wege. Wir finden einen versteckten Spielplatz. Die Bewegung an der Luft tut gut. Wir sind danach angenehm müde.',
    'Ich male ein Bild für meine Oma. Ich benutze viele glitzernde Farben. Es zeigt einen Engel im Himmel. Oma wird sich sicher sehr freuen. Geschenke machen glücklich.',
    'Wir spielen heute Verstecken im Haus. Ich finde ein sehr gutes Versteck. Mein Bruder sucht mich überall. Er läuft direkt an mir vorbei. Ich muss ganz leise kichern.',
    'Ich lese ein Comic über Superhelden. Der Held kann fliegen und ist stark. Er hilft Menschen in großer Gefahr. Die Bilder sind sehr spannend gemalt. Ich lese den Comic mehrmals.',
    'Wir bauen eine Höhle aus Decken. Wir nehmen Kissen und eine Taschenlampe. Drinnen ist es dunkel und gemütlich. Wir erzählen uns dort Geheimnisse. Unsere Höhle ist der beste Ort.',
    'Ich helfe beim Kochen in der Küche. Ich schneide die weichen Gurken. Ich wasche den grünen Salat ab. Wir bereiten ein gesundes Essen vor. Kochen ist eine tolle Aufgabe.',
    'Wir tanzen zur Musik im Wohnzimmer. Wir drehen uns schnell im Kreis. Wir machen lustige Bewegungen dazu. Das Tanzen macht uns richtig fröhlich. Wir haben viel Energie.',
    'Ich schaue mir die Wolken am Himmel an. Eine Wolke sieht aus wie ein Hund. Eine andere sieht aus wie ein Baum. Der Wind schiebt die Wolken weiter. Träumen unter blauem Himmel.',
    'Heute war ein wirklich toller Tag. Ich habe viel gelernt und gelacht. Ich freue mich auf den nächsten Tag. Ich kuschele mich in mein Bett. Schlaf gut und träum süß.'
];

// Extended Sentences (More complex)
export const extendedSentences: string[] = [
    // Ich + Erweiterung
    'Ich bin heute zu Hause.', 'Ich habe ein neues Buch.', 'Ich gehe heute in die Schule.',
    'Ich komme später nach Hause.', 'Ich sehe einen großen Hund.', 'Ich höre schöne Musik.',
    'Ich mache meine Hausaufgaben.', 'Ich spiele mit meinem Freund.',
    'Ich lerne Deutsch jeden Tag.', 'Ich lese ein spannendes Buch.',

    // Familie
    'Meine Mama ist zu Hause.', 'Mein Papa arbeitet viel.', 'Meine Oma kommt heute.',
    'Mein Opa liest die Zeitung.', 'Ich spiele mit meiner Schwester.', 'Ich helfe meiner Mama.',
    'Mein Bruder ist klein.', 'Meine Familie ist nett.', 'Wir essen zusammen.', 'Wir sind zu Hause.',

    // Schule
    'Ich gehe gern in die Schule.', 'Ich lerne neue Wörter.', 'Ich schreibe einen Satz.',
    'Ich lese laut im Unterricht.', 'Der Lehrer erklärt die Aufgabe.', 'Die Lehrerin hilft mir.',
    'Ich sitze neben meinem Freund.', 'Ich mache meine Aufgaben gut.',
    'Ich höre im Unterricht zu.', 'Ich frage den Lehrer.',

    // Haus
    'Ich bin allein zu Hause.', 'Ich komme ins Wohnzimmer.', 'Ich öffne das Fenster.',
    'Ich mache die Tür auf.', 'Ich räume mein Zimmer auf.', 'Ich spiele im Wohnzimmer.',
    'Ich sehe fern am Abend.', 'Ich helfe im Haushalt.', 'Ich gehe in mein Zimmer.',
    'Ich schlafe im Bett.',

    // Вещи
    'Das ist mein neues Buch.', 'Ich habe einen roten Ball.', 'Ich nehme meine Tasche.',
    'Ich lege das Buch auf den Tisch.', 'Ich finde mein Heft schnell.', 'Ich suche meinen Stift.',
    'Ich öffne mein Heft.', 'Ich schließe die Tasche.',

    // Еда
    'Ich esse gern Obst.', 'Ich trinke gern Wasser.', 'Ich esse ein Brot mit Käse.',
    'Ich trinke einen Apfelsaft.', 'Ich habe großen Hunger.', 'Ich habe Durst.',
    'Ich esse zusammen mit meiner Familie.', 'Ich nehme einen Apfel.',
    'Ich mag süßes Essen.', 'Ich will etwas trinken.',

    // Животные
    'Der Hund läuft schnell im Park.', 'Die Katze schläft auf dem Sofa.',
    'Der Vogel sitzt auf dem Baum.', 'Der Fisch schwimmt im Wasser.', 'Ich sehe ein kleines Tier.',
    'Ich habe einen Hund zu Hause.', 'Die Katze spielt mit mir.', 'Der Vogel fliegt hoch.',

    // Действия / Alltag
    'Ich spiele draußen im Garten.', 'Ich laufe schnell nach Hause.', 'Ich gehe langsam zur Schule.',
    'Ich bleibe heute hier.', 'Ich warte auf meinen Freund.', 'Ich komme gleich zurück.',
    'Ich helfe dir gern.', 'Ich höre dir zu.', 'Ich passe gut auf.', 'Ich mache alles richtig.',

    // Вежливость / общение
    'Guten Morgen, wie geht es dir?', 'Guten Tag, ich bin da.', 'Danke für deine Hilfe.',
    'Bitte hilf mir.', 'Vielen Dank für alles.', 'Nein, ich möchte nicht.', 'Ja, ich komme gern.',
    'Entschuldigung, ich verstehe nicht.',

    // Описания
    'Das Buch ist sehr interessant.', 'Der Ball ist groß und rot.', 'Mein Zimmer ist sauber.',
    'Das Haus ist schön.', 'Der Hund ist klein.', 'Die Katze ist schnell.',
    'Das Spiel ist neu.', 'Das Wetter ist gut.',

    // Вопросы
    'Wie heißt dein Freund?', 'Wo ist dein Buch?', 'Was machst du heute?',
    'Warum bist du hier?', 'Kommst du morgen?', 'Hast du Zeit heute?',
    'Willst du mit mir spielen?', 'Kannst du mir helfen?',

    // Эмоции
    'Ich bin heute sehr glücklich.', 'Ich bin ein bisschen müde.',
    'Ich bin krank und bleibe zu Hause.', 'Ich bin traurig heute.', 'Ich habe große Angst.',
    'Ich freue mich sehr.', 'Ich bin zufrieden.', 'Ich bin nervös.'
];

export const sentences = [...lolaSentences, ...extendedSentences];
export const allStories = [...lolaStoriesLvl3, ...lolaStoriesLvl4];
