export interface SynonymPair {
    word1: string;
    word2: string;
}

export const synonymsData: SynonymPair[] = [
    { word1: "fangen", word2: "haschen" },
    { word1: "gucken", word2: "sehen" },
    { word1: "rennen", word2: "laufen" },
    { word1: "sagen", word2: "sprechen" },
    { word1: "machen", word2: "tun" },
    { word1: "essen", word2: "speisen" },
    { word1: "trinken", word2: "schlürfen" },
    { word1: "weinen", word2: "heulen" },
    { word1: "lachen", word2: "kichern" },
    { word1: "flüstern", word2: "tuscheln" },
    { word1: "hauen", word2: "schlagen" },
    { word1: "bauen", word2: "errichten" },
    { word1: "malen", word2: "zeichnen" },
    { word1: "singen", word2: "trällern" },
    { word1: "hüpfen", word2: "springen" },
    { word1: "klettern", word2: "steigen" },
    { word1: "rutschen", word2: "gleiten" },
    { word1: "werfen", word2: "schleudern" },
    { word1: "holen", word2: "bringen" },
    { word1: "helfen", word2: "unterstützen" },
    { word1: "teilen", word2: "abgeben" },
    { word1: "spielen", word2: "zocken" },
    { word1: "schlafen", word2: "ratzen" },
    { word1: "aufwachen", word2: "munter werden" },
    { word1: "anziehen", word2: "bekleiden" },
    { word1: "putzen", word2: "reinigen" },
    { word1: "waschen", word2: "säubern" },
    { word1: "kochen", word2: "zubereiten" },
    { word1: "backen", word2: "braten" },
    { word1: "kaufen", word2: "erwerben" },
    { word1: "verkaufen", word2: "handeln" },
    { word1: "schenken", word2: "geben" },
    { word1: "freuen", word2: "jubeln" },
    { word1: "ärgern", word2: "nerven" },
    { word1: "fürchten", word2: "gruseln" },
    { word1: "träumen", word2: "phantasieren" },
    { word1: "denken", word2: "grübeln" },
    { word1: "wissen", word2: "kennen" },
    { word1: "lernen", word2: "üben" },
    { word1: "schreiben", word2: "notieren" },
    { word1: "lesen", word2: "schmökern" },
    { word1: "rechnen", word2: "zählen" },
    { word1: "fragen", word2: "erkundigen" },
    { word1: "antworten", word2: "erwidern" },
    { word1: "verstecken", word2: "verbergen" },
    { word1: "suchen", word2: "finden" },
    { word1: "verlieren", word2: "verlegen" },
    { word1: "gewinnen", word2: "siegen" },
    { word1: "feiern", word2: "party machen" },
    { word1: "tanzen", word2: "shaken" }
];
