const translationsLvl4 = {
    'Der kleine Hamster Goldi hamstert Körner. Er füllt seine Backen ganz voll. In seinem Häuschen leert er sie aus. Jetzt hat er einen großen Vorrat. Goldi ist ein fleißiges Tier.': 'Маленький хомячок Голди запасает зерно. Он набивает щеки до отказа. В своем домике он их высыпает. Теперь у него есть большой запас. Голди — трудолюбивое животное.',
    'Die Schildkröte Susi läuft sehr langsam. Sie trägt ihr hartes Haus auf dem Rücken. Wenn sie Angst hat, zieht sie den Kopf ein. Susi frisst gern frischen Salat. Sie sonnt sich auf einem Stein.': 'Черепаха Зюзи ползет очень медленно. Она носит свой твердый домик на спине. Когда ей страшно, она втягивает голову. Зюзи любит есть свежий салат. Она греется на камне.',
    'Der bunte Papagei kann sprechen. Er sagt laut: "Hallo, wie geht es dir?". Er hat grüne und rote Federn. Er fliegt im Käfig hin und her. Alle Kinder staunen über den Vogel.': 'Разноцветный попугай умеет говорить. Он громко говорит: "Привет, как дела?". У него зеленые и красные перья. Он летает по клетке туда-сюда. Все дети удивляются птице.',
    'Das kleine Kätzchen spielt mit einer Feder. Es springt hoch in die Luft. Dann rollt es sich auf dem Teppich. Es schnurrt ganz leise vor Glück. Kätzchen sind sehr verspielt.': 'Маленький котенок играет с перышком. Он прыгает высоко в воздух. Затем он катается по ковру. Он тихонько мурлычет от счастья. Котята очень игривы.',
    'Im Wald lebt ein brauner Bär. Er sucht nach süßem Honig. Die Bienen fliegen um ihn herum. Der Bär hat ein dickes Fell. Er schläft im Winter in einer Höhle.': 'В лесу живет коричневый медведь. Он ищет сладкий мед. Пчелы летают вокруг него. У медведя густая шерсть. Зимой он спит в берлоге.',
    'Ein kleiner Elefant spritzt mit Wasser. Er benutzt seinen Rüssel wie eine Dusche. Das macht ihm bei der Hitze Spaß. Seine Ohren wackeln hin und her. Er ist das größte Tier im Zoo.': 'Маленький слоненок брызгается водой. Он использует свой хобот как душ. Это доставляет ему удовольствие в жару. Его уши качаются туда-сюда. Он самое большое животное в зоопарке.',
    'Die Giraffe hat einen sehr langen Hals. Sie frisst die Blätter oben am Baum. Niemand sonst kommt so hoch wie sie. Ihr Fell hat braune Flecken. Sie läuft elegant über die Wiese.': 'У жирафа очень длинная шея. Она ест листья на верхушке дерева. Никто другой не забирается так высоко, как она. На ее шерсти коричневые пятна. Она элегантно бежит по лугу.',
    'Der Fuchs schleicht leise durch das Gebüsch. Er hat einen buschigen, roten Schwanz. Seine Augen leuchten in der Nacht. Er sucht nach einer kleinen Maus. Der Fuchs ist sehr schlau.': 'Лиса тихо крадется через кусты. У нее пушистый рыжий хвост. Ее глаза светятся в темноте. Она ищет маленькую мышку. Лиса очень хитрая.',
    'Im Teich schwimmt ein goldener Fisch. Seine Schuppen glänzen im Sonnenlicht. Er macht kleine Blasen im Wasser. Er versteckt sich unter einem Blatt. Das Wasser ist ganz ruhig.': 'В пруду плавает золотая рыбка. Ее чешуя блестит на солнце. Она пускает маленькие пузырьки в воде. Она прячется под листком. Вода совсем спокойная.',
    'Der Pinguin watschelt über das kalte Eis. Er trägt einen schwarz-weißen Frack. Im Wasser schwimmt er sehr schnell. Er springt mutig in die Wellen. Pinguine lieben den kalten Winter.': 'Пингвин ковыляет по холодному льду. На нем черно-белый фрак. В воде он плавает очень быстро. Он смело прыгает в волны. Пингвины любят холодную зиму.',
    'Ein kleiner Marienkäfer sitzt auf meiner Hand. Er hat sechs Beine und viele Punkte. Vorsichtig krabbelt er an meinem Finger. Dann breitet er seine Flügel aus. Er fliegt hoch in den Himmel.': 'Маленькая божья коровка сидит на моей руке. У нее шесть ножек и много точек. Она осторожно ползет по моему пальцу. Затем она расправляет крылья. Она летит высоко в небо.',
    'Der Hase hoppelt schnell über das Feld. Er hat lange Ohren und eine Stupsnase. Er sucht nach einer saftigen Karotte. Wenn er etwas hört, bleibt er stehen. Hasen können sehr gut hören.': 'Заяц быстро скачет по полю. У него длинные уши и нос пуговкой. Он ищет сочную морковку. Когда он что-то слышит, он останавливается. Зайцы умеют очень хорошо слышать.',
    'Die Spinne webt ein kunstvolles Netz. Es glänzt im Morgentau wie Diamanten. Die Spinne wartet in der Mitte. Sie ist eine geduldige Jägerin. Insekten fliegen in das klebrige Netz.': 'Паук плетет искусную сеть. Она блестит в утренней росе, как алмазы. Паук ждет посередине. Она терпеливая охотница. Насекомые залетают в липкую сеть.',
    'Eine kleine Maus knabbert am Käse. Sie macht ganz leise Geräusche. Plötzlich hört sie ein Geräusch. Schnell rennt sie in ihr Loch. Dort ist sie sicher vor der Katze.': 'Маленькая мышка грызет сыр. Она издает очень тихие звуки. Вдруг она слышит шум. Она быстро бежит в свою норку. Там она в безопасности от кошки.',
    'Der Wolf heult laut im Mondschein. Seine Freunde antworten ihm aus der Ferne. Das klingt ein bisschen unheimlich. Wölfe leben zusammen in einem Rudel. Sie sind sehr starke Tiere.': 'Волк громко воет при лунном свете. Друзья отвечают ему издалека. Это звучит немного жутковато. Волки живут вместе в стае. Это очень сильные животные.',
    'Im Stall wiehert das weiße Pferd. Es wartet auf seinen Hafer. Ich bürste sein glänzendes Fell. Das Pferd schüttelt seine lange Mähne. Es freut sich auf unseren Ausritt.': 'В конюшне ржет белая лошадь. Она ждет свой овес. Я чищу ее блестящую шерсть. Лошадь трясет своей длинной гривой. Она радуется нашей прогулке верхом.',
    'Die Biene summt von Blume zu Blume. Sie sammelt gelben Blütenstaub. Daraus machen die Bienen süßen Honig. Die Königin wohnt im Bienenstock. Bienen sind sehr nützliche Tiere.': 'Пчела жужжит от цветка к цветку. Она собирает желтую цветочную пыльцу. Из нее пчелы делают сладкий мед. Королева живет в улье. Пчелы — очень полезные животные.',
    'Ein kleiner Igel rollt sich zusammen. Er zeigt seine vielen spitzen Stacheln. So schützt er sich vor Gefahren. Er sucht unter Blättern nach Futter. Im Winter hält er Winterschlaf.': 'Маленький ежик сворачивается в клубок. Он показывает свои многочисленные острые иголки. Так он защищается от опасностей. Он ищет еду под листьями. Зимой он впадает в спячку.',
    'Das Schaf hat eine dicke, weiße Wolle. Es frisst das grüne Gras auf der Weide. Das kleine Lamm springt fröhlich herum. Der Hirte passt gut auf die Herde auf. Schafe sind friedliche Tiere.': 'У овцы густая белая шерсть. Она ест зеленую траву на пастбище. Маленький ягненок весело прыгает вокруг. Пастух хорошо присматривает за стадом. Овцы — мирные животные.',
    'Im Zoo sehen wir einen Tiger. Er hat schwarze Streifen im Fell. Seine Tatzen sind sehr groß. Er gähnt und zeigt seine Zähne. Der Tiger ist eine wilde Raubkatze.': 'В зоопарке мы видим тигра. У него черные полосы на шерсти. Его лапы очень большие. Он зевает и показывает зубы. Тигр — дикая хищная кошка.',
    'In der Schule schreiben wir heute ein Diktat. Ich spitze meinen Bleistift ganz vorsichtig. Ich konzentriere mich auf jedes Wort. Der Lehrer schreibt an die Tafel. Ich habe keine Fehler gemacht.': 'В школе мы сегодня пишем диктант. Я очень осторожно точу свой карандаш. Я концентрируюсь на каждом слове. Учитель пишет на доске. Я не сделал ни одной ошибки.',
    'In der Pause spielen wir Fangen. Wir rennen über den großen Schulhof. Alle Kinder lachen und rufen laut. Die Glocke läutet das Ende ein. Wir gehen ordentlich zurück ins Klassenzimmer.': 'На перемене мы играем в догонялки. Мы бегаем по большому школьному двору. Все дети смеются и громко кричат. Колокольчик возвещает о конце перемены. Мы организованно возвращаемся в класс.',
    'In Kunst malen wir mit Wasserfarben. Ich mische Blau und Gelb zu Grün. Mein Bild zeigt eine bunte Blumenwiese. Die Farben trocknen langsam auf dem Papier. Malen macht mir sehr viel Spaß.': 'На уроке рисования мы рисуем акварелью. Я смешиваю синий и желтый, чтобы получить зеленый. На моей картинке изображен пестрый цветочный луг. Краски медленно сохнут на бумаге. Рисование доставляет мне много удовольствия.',
    'Im Sportunterricht turnen wir heute. Wir klettern an der hohen Sprossenwand. Ich schaffe es bis ganz nach oben. Das erfordert viel Kraft und Mut. Wir machen auch eine Purzelbaum.': 'На физкультуре мы сегодня занимаемся гимнастикой. Мы лазаем по высокой шведской стенке. Я добираюсь до самого верха. Это требует много силы и мужества. Мы также кувыркаемся.',
    'In der Bibliothek leihe ich ein Buch aus. Es geht um Sterne und Planeten. Ich lese es heute Abend im Bett. Das Buch hat viele tolle Fotos. Ich lerne viel über das Weltall.': 'В библиотеке я беру книгу. Она о звездах и планетах. Я почитаю ее сегодня вечером в постели. В книге много отличных фотографий. Я узнаю много нового о космосе.',
    'Wir rechnen heute schwierige Aufgaben. Plus und Minus sind für mich einfach. Der Lehrer lobt meine saubere Schrift. Ich helfe meinem Nachbarn bei einer Aufgabe. Mathe ist mein Lieblingsfach.': 'Мы сегодня решаем трудные задачи. Плюс и минус для меня — это просто. Учитель хвалит мой чистый почерк. Я помогаю соседу с задачей. Математика — мой любимый предмет.',
    'In Sachkunde lernen wir über Bäume. Wir sammeln bunte Blätter im Wald. Ich weiß jetzt, wie eine Eiche aussieht. Wir kleben die Blätter in unser Heft. Die Natur ist sehr interessant.': 'На природоведении мы изучаем деревья. Мы собираем разноцветные листья в лесу. Теперь я знаю, как выглядит дуб. Мы вклеиваем листья в нашу тетрадь. Природа очень интересна.',
    'Im Musikraum singen wir ein neues Lied. Der Lehrer spielt dazu auf dem Klavier. Unsere Stimmen klingen zusammen sehr schön. Wir klatschen im Rhythmus der Musik. Singen macht gute Laune.': 'В музыкальном классе мы поем новую песню. Учитель подыгрывает на пианино. Наши голоса звучат вместе очень красиво. Мы хлопаем в ритм музыки. Пение создает хорошее настроение.',
    'Ich habe meine Hausaufgaben schon gemacht. Ich habe Sätze über den Sommer geschrieben. Meine Mutter kontrolliert meine Fehler. Morgen zeige ich das Heft dem Lehrer. Ich bin gut vorbereitet.': 'Я уже сделал домашнее задание. Я написал предложения о лете. Моя мама проверяет мои ошибки. Завтра я покажу тетрадь учителю. Я хорошо подготовился.',
    'Mein Schulranzen ist heute sehr schwer. Ich habe viele Bücher und Hefte dabei. Auch meine Brotdose ist gut gefüllt. Ich trage den Ranzen auf dem Rücken. Der Weg zur Schule ist kurz.': 'Мой школьный ранец сегодня очень тяжелый. У меня с собой много книг и тетрадей. Мой контейнер для еды тоже хорошо наполнен. Я несу ранец на спине. Дорога в школу короткая.',
    'In der Schule haben wir ein neues Aquarium. Es schwimmen bunte Fische darin. Wir dürfen die Fische jeden Tag füttern. Das Wasser muss immer sauber sein. Wir beobachten die Tiere gern.': 'В школе у нас новый аквариум. В нем плавают разноцветные рыбки. Нам разрешают кормить рыбок каждый день. Вода всегда должна быть чистой. Мы любим наблюдать за животными.',
    'Heute machen wir ein gemeinsames Frühstück. Jeder bringt etwas Gesundes von zu Hause mit. Wir essen Äpfel, Brot und Käse. Zusammen schmeckt es uns viel besser. Wir unterhalten uns dabei nett.': 'Сегодня у нас совместный завтрак. Каждый приносит что-то полезное из дома. Мы едим яблоки, хлеб и сыр. Вместе нам намного вкуснее. Мы при этом мило беседуем.',
    'Wir basteln Laternen für das Fest. Wir benutzen buntes Papier und Kleber. Meine Laterne sieht aus wie eine Sonne. Wir freuen uns auf den Umzug am Abend. Das Licht leuchtet hell.': 'Мы мастерим фонарики для праздника. Мы используем цветную бумагу и клей. Мой фонарик похож на солнце. Мы ждем вечернего шествия. Свет сияет ярко.',
    'Im Klassenraum stehen viele bunte Stühle. Wir sitzen an unseren großen Tischen. An der Wand hängen unsere Bilder. Wir halten unseren Raum immer sauber. Hier lernen wir jeden Tag.': 'В классе стоит много разноцветных стульев. Мы сидим за нашими большими столами. На стене висят наши рисунки. Мы всегда держим наш кабинет в чистоте. Здесь мы учимся каждый день.',
    'Ich habe eine neue Federmappe bekommen. Darin sind bunte Stifte und ein Lineal. Auch ein Radiergummi ist dabei. Ich ordne meine Stifte nach Farben. Alles ist nun griffbereit.': 'Мне подарили новый пенал. В нем цветные карандаши и линейка. Ластик там тоже есть. Я раскладываю карандаши по цветам. Теперь всё под рукой.',
    'Wir lernen heute ein neues Gedicht auswendig. Ich sage die Verse leise vor mich hin. Es geht um den bunten Herbstwind. Morgen sage ich es der Klasse vor. Ich bin ein bisschen aufgeregt.': 'Мы сегодня учим новое стихотворение наизусть. Я тихонько повторяю стихи про себя. Оно о пестром осеннем ветре. Завтра я буду рассказывать его классу. Я немного волнуюсь.',
    'In der Schule gibt es eine große Pause. Wir bekommen frische Milch zum Trinken. Das stärkt uns für die nächsten Stunden. Wir spielen zusammen mit dem Seil. Die Zeit vergeht sehr schnell.': 'В школе есть большая перемена. Нам дают пить свежее молоко. Это подкрепляет нас на следующие уроки. Мы вместе играем со скакалкой. Время проходит очень быстро.',
    'Wir machen heute ein Experiment mit Wasser. Wir schauen, was schwimmt und was sinkt. Ein Stein sinkt sofort nach unten. Ein Blatt schwimmt oben auf. Das ist sehr spannend.': 'Мы сегодня проводим эксперимент с водой. Мы смотрим, что плавает, а что тонет. Камень сразу опускается на дно. Листик плавает наверху. Это очень увлекательно.',
    'Der Lehrer erzählt uns eine alte Sage. Es geht um Ritter und ein Schloss. Wir hören alle ganz aufmerksam zu. Ich stelle mir die Geschichte bildlich vor. Geschichten erzählen ist toll.': 'Учитель рассказывает нам старую легенду. Она о рыцарях и замке. Мы все слушаем очень внимательно. Я представляю историю в картинках. Рассказывать истории — это здорово.',
    'Ich habe eine Eins in der Mathearbeit. Mein Vater freut sich sehr über die Note. Er schenkt mir ein kleines Spielzeug. Ich nehme mir vor, weiter fleißig zu lernen. Erfolg macht stolz.': 'У меня пятерка за контрольную по математике. Мой папа очень рад оценке. Он дарит мне маленькую игрушку. Я обещаю себе учиться прилежно и дальше. Успех вызывает гордость.',
    'Am Wochenende besuchen wir meine Oma. Sie wohnt in einem kleinen Dorf. Wir backen zusammen einen leckeren Apfelkuchen. Der Duft zieht durch das ganze Haus. Oma erzählt mir alte Geschichten.': 'На выходных мы навещаем мою бабушку. Она живет в маленькой деревне. Мы вместе печем вкусный яблочный пирог. Аромат разносится по всему дому. Бабушка рассказывает мне старые истории.',
    'Mein Papa repariert heute mein Fahrrad. Die Kette war locker und der Reifen platt. Jetzt glänzt das Rad wieder wie neu. Ich mache eine Probefahrt im Garten. Danke für die Hilfe, Papa!': 'Мой папа сегодня чинит мой велосипед. Цепь болталась, а шина сдулась. Теперь велосипед снова блестит как новый. Я совершаю пробную поездку в саду. Спасибо за помощь, папа!',
    'Meine kleine Schwester lernt gerade laufen. Sie macht ihre ersten vorsichtigen Schritte. Ich halte sie fest an der Hand. Sie lacht und freut sich sehr. Wir sind alle stolz auf sie.': 'Моя младшая сестра как раз учится ходить. Она делает свои первые осторожные шаги. Я крепко держу ее за руку. Она смеется и очень радуется. Мы все гордимся ею.',
    'Wir räumen heute gemeinsam die Wohnung auf. Ich sortiere meine Spielsachen im Kinderzimmer. Meine Mutter staubsaugt den dicken Teppich. Danach ist alles wieder ordentlich und sauber. Ordnung muss sein.': 'Сегодня мы вместе убираем квартиру. Я сортирую свои игрушки в детской. Моя мама пылесосит густой ковер. После этого всё снова аккуратно и чисто. Порядок должен быть.',
    'Abends lesen wir zusammen ein Buch. Ich darf mir eine Geschichte aussuchen. Mein Vater liest mit verstellter Stimme vor. Ich kuschele mich in meine Decke. Das ist mein liebstes Ritual.': 'Вечером мы вместе читаем книгу. Я могу сам выбрать историю. Мой папа читает измененным голосом. Я уютно укутываюсь в одеяло. Это мой любимый ритуал.',
    'Wir kochen heute Nudeln mit Tomatensoße. Ich darf den Käse über das Essen streuen. Die Soße duftet nach frischen Kräutern. Wir decken gemeinsam den großen Tisch. Guten Appetit an alle!': 'Мы сегодня готовим макароны с томатным соусом. Мне разрешают посыпать еду сыром. Соус пахнет свежими травами. Мы вместе накрываем большой стол. Всем приятного аппетита!',
    'In unserem Garten blühen rote Rosen. Ich helfe meiner Mutter beim Gießen. Die Erde riecht nach dem frischen Wasser. Ein kleiner Vogel badet in einer Pfütze. Der Garten ist ein schöner Ort.': 'В нашем саду цветут красные розы. Я помогаю маме с поливом. Земля пахнет свежей водой. Маленькая птичка купается в луже. Сад — прекрасное место.',
    'Wir machen einen Ausflug in den Wald. Wir suchen nach Pilzen und Kastanien. Die Luft riecht nach Moos und Blättern. Wir hören das Klopfen eines Spechtes. Der Wald ist voller Wunder.': 'Мы идем на прогулку в лес. Мы ищем грибы и каштаны. Воздух пахнет мхом и листьями. Мы слышим стук дятла. Лес полон чудес.',
    'Heute kommen meine Freunde zu Besuch. Wir spielen im Zimmer mit den Bausteinen. Wir bauen eine riesige Stadt mit Autos. Danach essen wir zusammen ein Eis. Es ist ein toller Nachmittag.': 'Сегодня ко мне в гости приходят друзья. Мы играем в комнате с кубиками. Мы строим огромный город с машинами. Потом мы вместе едим мороженое. Это отличный день.',
    'Mein Opa hat eine große Werkstatt. Dort baut er schöne Dinge aus Holz. Er zeigt mir, wie man einen Nagel einschlägt. Ich darf ihm beim Sägen helfen. Ich lerne viel von meinem Opa.': 'У моего дедушки большая мастерская. Там он делает красивые вещи из дерева. Он показывает мне, как забивать гвоздь. Мне разрешают помогать ему пилить. Я многому учусь у своего дедушки.',
    'Wir feiern heute ein großes Familienfest. Alle meine Tanten und Onkel kommen. Es gibt viel Musik und gutes Essen. Wir tanzen zusammen im Wohnzimmer. Alle sind fröhlich und lachen.': 'Мы празднуем сегодня большой семейный праздник. Приезжают все мои тети и дяди. Много музыки и хорошей еды. Мы вместе танцуем в гостиной. Все веселы и смеются.',
    'Ich habe ein eigenes Zimmer bekommen. Die Wände sind hellblau gestrichen. Mein Bett steht direkt am Fenster. Ich habe dort Platz für meine Spielsachen. Ich fühle mich hier sehr wohl.': 'У меня появилась собственная комната. Стены выкрашены в голубой цвет. Моя кровать стоит прямо у окна. Там у меня есть место для игрушек. Я чувствую себя здесь очень уютно.',
    'Wir schauen uns alte Fotos an. Ich sehe meine Eltern als Kinder. Sie sahen damals ganz anders aus. Wir lachen über die lustige Kleidung. Erinnerungen sind etwas Schönes.': 'Мы смотрим старые фотографии. Я вижу своих родителей детьми. Тогда они выглядели совсем иначе. Мы смеемся над смешной одеждой. Воспоминания — это что-то прекрасное.',
    'Meine Mutter näht mir ein Kostüm. Ich möchte an Karneval ein Tiger sein. Der Stoff ist weich und gestreift. Ich probiere das Kostüm heute an. Es passt mir ganz genau.': 'Моя мама шьет мне костюм. Я хочу быть тигром на карнавале. Ткань мягкая и полосатая. Я примеряю костюм сегодня. Он мне как раз в пору.',
    'Wir gehen heute zusammen einkaufen. Wir brauchen Milch, Eier und frisches Brot. Ich darf den kleinen Einkaufswagen schieben. Wir finden alles auf unserer Liste. Einkaufen ist wie eine Suche.': 'Мы сегодня идем за покупками вместе. Нам нужны молоко, яйца и свежий хлеб. Мне разрешают везти маленькую тележку. Мы находим всё по нашему списку. Покупки — это как поиск сокровищ.',
    'Mein Bruder und ich spielen Fußball. Wir schießen Tore auf der Wiese. Manchmal gewinne ich, manchmal er. Das Wichtigste ist der gemeinsame Spaß. Wir sind ein gutes Team.': 'Мы с братом играем в футбол. Мы забиваем голы на лугу. Иногда выигрываю я, иногда он. Самое главное — это совместное веселье. Мы хорошая команда.',
    'Wir zünden eine Kerze am Abend an. Das Licht flackert warm und hell. Wir unterhalten uns über den Tag. Es ist gemütlich in unserem Haus. Wir genießen die gemeinsame Zeit.': 'Вечером мы зажигаем свечу. Свет мерцает тепло и ярко. Мы беседуем о прошедшем дне. В нашем доме уютно. Мы наслаждаемся временем, проведенным вместе.',
    'Ich helfe beim Decken des Tisches. Ich lege Messer, Gabel und Löffel bereit. Auch die bunten Servietten dürfen nicht fehlen. Alles sieht nun sehr einladend aus. Das Essen ist fast fertig.': 'Я помогаю накрывать на стол. Я раскладываю ножи, вилки и ложки. Цветные салфетки тоже не должны отсутствовать. Теперь всё выглядит очень заманчиво. Еда почти готова.',
    'Wir waschen heute zusammen das Auto. Wir benutzen viel Schaum und Wasser. Die Seifenblasen fliegen in der Luft. Das Auto glänzt danach in der Sonne. Wir sind beide nass geworden.': 'Мы сегодня вместе моем машину. Мы используем много пены и воды. Мыльные пузыри летают в воздухе. После этого машина блестит на солнце. Мы оба промокли.',
    'Meine Oma strickt mir warme Socken. Die Wolle ist bunt und sehr weich. Sie benutzt vier lange Stricknadeln. Die Socken halten meine Füße warm. Ich danke meiner Oma sehr.': 'Моя бабушка вяжет мне теплые носки. Шерсть пестрая и очень мягкая. Она использует четыре длинные спицы. Носки согревают мои ноги. Я очень благодарен своей бабушке.',
    'Die Sonne scheint hell am Himmel. Die Vögel zwitschern in den Bäumen. Ich gehe ohne Jacke nach draußen. Alles ist grün und voller Leben. Der Sommer ist endlich da.': 'Солнце ярко светит на небе. Птицы щебечут на деревьях. Я выхожу на улицу без куртки. Всё зелено и полно жизни. Наконец-то пришло лето.',
    'Der Regen prasselt gegen die Scheibe. Ich trage meine gelben Gummistiefel. Ich springe mutig in eine tiefe Pfütze. Das Wasser spritzt nach allen Seiten. Ich werde gar nicht nass.': 'Дождь барабанит по стеклу. На мне мои желтые резиновые сапоги. Я смело прыгаю в глубокую лужу. Вода разлетается во все стороны. Я совсем не мокну.',
    'Der Wind bläst stark durch die Haare. Ich lasse meinen Drachen steigen. Er fliegt hoch über den Feldern. Ich muss die Schnur fest halten. Der Wind ist heute sehr kräftig.': 'Ветер сильно дует в волосы. Я запускаю своего воздушного змея. Он летает высоко над полями. Я должен крепко держать веревку. Ветер сегодня очень сильный.',
    'Der erste Schnee fällt leise nieder. Die Welt sieht aus wie gepudert. Wir bauen einen dicken Schneemann. Er bekommt eine Nase aus einer Karotte. Der Winter ist wunderschön.': 'Первый снег тихо падает на землю. Мир выглядит как припудренный. Мы строим толстого снеговика. У него будет нос из морковки. Зима прекрасна.',
    'Im Herbst färben sich die Blätter. Sie leuchten in Rot, Gelb und Braun. Sie fallen langsam von den Bäumen. Ich sammle die schönsten Blätter ein. Der Wald ist nun bunt.': 'Осенью листья меняют цвет. Они сияют красным, желтым и коричневым. Они медленно падают с деревьев. Я собираю самые красивые листья. Лес теперь пестрый.',
    'Der Regenbogen hat many Farben. Er erscheint nach einem kurzen Schauer. Er verbindet den Himmel mit der Erde. Ich versuche, das Ende zu finden. Ein Wunder der Natur.': 'У радуги много цветов. Она появляется после короткого ливня. Она соединяет небо с землей. Я пытаюсь найти ее край. Чудо природы.',
    'Die Sterne funkeln in der Nacht. Der Mond sieht aus wie eine Sichel. Es ist ganz still im Garten. Ich schaue aus meinem Fenster hoch. Das Weltall ist unendlich groß.': 'Звезды сверкают ночью. Луна похожа на серп. В саду совсем тихо. Я смотрю в свое окно наверх. Вселенная бесконечно велика.',
    'Der Donner grollt laut in der Ferne. Ein Blitz zuckt hell am Himmel. Wir bleiben sicher im warmen Haus. Das Gewitter zieht schnell an uns vorbei. Die Natur zeigt ihre Kraft.': 'Гром громко грохочет вдали. Молния ярко сверкает в небе. Мы остаемся в безопасности в теплом доме. Гроза быстро проходит мимо нас. Природа показывает свою мощь.',
    'Die Blumen duften herrlich auf der Wiese. Viele Bienen fliegen von Kelch zu Kelch. Ich pflücke einen bunten Strauß. Er steht jetzt in einer Vase. Der Frühling ist erwacht.': 'Цветы чудесно пахнут на лугу. Множество пчел летают от чашечки к чашечке. Я собираю пестрый букет. Теперь он стоит в вазе. Весна пробудилась.',
    'Das Meer rauscht beruhigend am Strand. Die Wellen schlagen sanft an das Ufer. Ich sammle kleine, glatte Steine. Das Wasser ist angenehm und kühl. Ich liebe den Urlaub am Meer.': 'Море успокаивающе шумит на пляже. Волны мягко бьются о берег. Я собираю маленькие гладкие камни. Вода приятная и прохладная. Я люблю отдых на море.',
    'Der Nebel liegt dicht über den Feldern. Man kann nicht sehr weit sehen. Alles wirkt geheimnisvoll und grau. Die Sonne kämpft sich langsam durch. Ein kühler Morgen bricht an.': 'Туман густо лежит над полями. Видно не очень далеко. Всё кажется таинственным и серым. Солнце медленно пробивается сквозь него. Настает прохладное утро.',
    'Im Wald suchen wir nach Tierspuren. Ich finde den Abdruck von einem Reh. Wir bewegen uns ganz leise. Das Moos ist weich wie ein Teppich. Wir entdecken viele kleine Geheimnisse.': 'В лесу мы ищем следы животных. Я нахожу отпечаток ноги косули. Мы движемся очень тихо. Мох мягкий, как ковер. Мы открываем много маленьких секретов.',
    'Die Sonne geht langsam unter. Der Himmel färbt sich orange und violett. Es wird nun kühler im Garten. Die ersten Grillen fangen an zu zirpen. Der Tag neigt sich dem Ende.': 'Солнце медленно садится. Небо окрашивается в оранжевый и фиолетовый цвета. В саду становится прохладнее. Первые сверчки начинают стрекотать. День клонится к закату.',
    'Wir pflanzen einen kleinen Apfelbaum. Wir graben ein tiefes Loch in die Erde. Der Baum braucht viel Wasser und Licht. In ein paar Jahren ernten wir Äpfel. Wir pflegen den Baum gut.': 'Мы сажаем маленькую яблоню. Мы копаем глубокую яму в земле. Дереву нужно много воды и света. Через несколько лет мы будем собирать яблоки. Мы хорошо ухаживаем за деревом.',
    'Der Bach plätschert über kleine Steine. Das Wasser ist klar und sehr kalt. Ich baue ein kleines Schiff aus Rinde. Es treibt schnell mit der Strömung. Der Bach führt zum großen See.': 'Ручей журчит по маленьким камням. Вода прозрачная и очень холодная. Я строю маленький кораблик из коры. Он быстро плывет по течению. Ручей ведет к большому озеру.',
    'Im Winter sind die Fenster gefroren. Es gibt dort wunderschöne Eisblumen. Ich male mit dem Finger ein Herz. Die Kälte beißt in meine Nase. Drinnen ist es warm und gemütlich.': 'Зимой окна замерзли. На них выросли прекрасные ледяные узоры. Я рисую пальцем сердечко. Мороз кусает меня за нос. Внутри тепло и уютно.',
    'Wir beobachten die Ameisen im Garten. Sie tragen schwere Lasten zu ihrem Bau. Sie arbeiten alle fleißig zusammen. Der Ameisenhaufen ist sehr groß. Kleine Tiere mit großer Kraft.': 'Мы наблюдаем за муравьями в саду. Они тащат тяжелые грузы в свой муравейник. Они все прилежно работают вместе. Муравейник очень большой. Маленькие животные с большой силой.',
    'Ein Schmetterling setzt sich auf eine Blume. Seine Flügel sind blau und schwarz. Er saugt den süßen Nektar. Dann fliegt er leichtfüßig weiter. Die Natur ist voller Farben.': 'Бабочка садится на цветок. Ее крылья синие с черным. Она сосет сладкий нектар. Затем она легко улетает дальше. Природа полна красок.',
    'Wir sammeln bunte Kastanien im Park. Wir basteln daraus kleine Männchen. Wir benutzen Streichhölzer für die Beine. Das ist eine tolle herbstliche Idee. Wir freuen uns über die Figuren.': 'Мы собираем пестрые каштаны в парке. Мы мастерим из них маленьких человечков. Мы используем спички для ножек. Это отличная осенняя идея. Мы радуемся фигуркам.',
    'Der Mond leuchtet hell durch die Bäume. Er begleitet mich auf meinem Weg. Die Nacht ist friedlich und still. Ich träume von fernen Ländern. Gute Nacht an die ganze Welt.': 'Луна ярко светит сквозь деревья. Она сопровождает меня на моем пути. Ночь мирная и тихая. Я мечтаю о далеких странах. Спокойной ночи всему миру.',
    'Ich lerne heute ein neues Instrument. Es ist eine kleine, hölzerne Flöte. Ich übe die ersten einfachen Töne. Meine Eltern hören mir aufmerksam zu. Musik zu machen ist wunderbar.': 'Я сегодня учусь играть на новом инструменте. Это маленькая деревянная флейта. Я разучиваю первые простые звуки. Мои родители внимательно слушают меня. Заниматься музыкой — это чудесно.',
    'Wir gehen heute ins Schwimmbad. Ich springe vom kleinen Brett ins Wasser. Ich kann schon ein bisschen schwimmen. Das Wasser spritzt mir in die Augen. Schwimmen ist mein liebstes Hobby.': 'Мы идем сегодня в бассейн. Я прыгаю с маленькой вышки в воду. Я уже немного умею плавать. Вода брызгает мне в глаза. Плавание — мое любимое хобби.',
    'Ich baue ein Modell aus kleinen Steinen. Es wird ein großes, weißes Schloss. Ich brauche viel Geduld und Zeit. Am Ende steht das Schloss stolz da. Ich habe es ganz allein gebaut.': 'Я строю модель из маленьких камней. Это будет большой белый замок. Мне нужно много терпения и времени. В конце замок гордо стоит. Я построил его совершенно один.',
    'Wir backen heute bunte Plätzchen. Wir stechen Sterne, Herzen und Monde aus. Der Teig schmeckt auch roh sehr gut. Danach verzieren wir sie mit Zucker. Die Küche duftet herrlich.': 'Мы сегодня печем разноцветное печенье. Мы вырезаем звезды, сердечки и полумесяцы. Тесто очень вкусное и в сыром виде. Затем мы украшаем их сахаром. На кухне пахнет чудесно.',
    'Ich schreibe eine Geschichte über Drachen. Der Drache kann blaues Feuer spucken. Er rettet eine Prinzessin aus Not. Meine Fantasie kennt keine Grenzen. Schreiben ist wie eine Reise.': 'Я пишу историю о драконах. Дракон умеет дышать синим огнем. Он спасает принцессу из беды. Моя фантазия не знает границ. Писать — это как путешествие.',
    'Wir spielen heute ein Brettspiel. Ich würfele eine Sechs und ziehe vor. Mein Bruder hat leider kein Glück. Wir lachen zusammen über den Spielzug. Gewinnen ist nicht das Wichtigste.': 'Мы сегодня играем в настольную игру. Мне выпадает шестерка, и я хожу вперед. Моему брату, к сожалению, не везет. Мы вместе смеемся над ходом. Победа — не самое главное.',
    'Ich sammle bunte Sticker in einem Album. Ich tausche doppelte Bilder mit Freunden. Mein Album ist schon fast voll. Ich ordne sie nach verschiedenen Themen. Das Sammeln macht mir Freude.': 'Я собираю цветные наклейки в альбом. Я обмениваюсь повторными картинками с друзьями. Мой альбом уже почти полон. Я раскладываю их по разным темам. Коллекционирование доставляет мне радость.',
    'Wir gehen heute auf den Spielplatz. Ich schaukele so hoch ich kann. Die Luft weht mir um die Nase. Danach rutsche ich die steile Bahn. Der Spielplatz ist ein Abenteuer.': 'Мы идем сегодня на игровую площадку. Я качаюсь так высоко, как только могу. Воздух обдувает мой нос. Затем я скатываюсь с крутой горки. Площадка — это целое приключение.',
    'Ich mache heute ein Puzzle mit vielen Teilen. Ich suche zuerst die Randstücke heraus. Langsam entsteht ein buntes Bild. Es zeigt viele Tiere im Urwald. Ich habe das Puzzle geschafft.': 'Я сегодня собираю пазл из множества деталей. Сначала я выбираю краевые кусочки. Медленно вырисовывается пестрая картинка. На ней много животных в джунглях. Я справился с пазлом.',
    'Wir basteln ein Schiff aus einem Karton. Wir benutzen Segel aus altem Stoff. Das Schiff heißt "Wilder Pirat". Wir lassen es in der Wanne schwimmen. Ahoi, kleine Kapitäne!': 'Мы мастерим корабль из картона. Мы используем паруса из старой ткани. Корабль называется "Дикий пират". Мы пускаем его плавать в ванне. Ахой, маленькие капитаны!',
    'Ich lerne heute einen Zaubertrick. Ich lasse eine Münze verschwinden. Meine Freunde schauen ganz genau hin. Sie wissen nicht, wie es geht. Ich bin ein kleiner Zauberer.': 'Я сегодня учу волшебный фокус. Я заставляю монету исчезнуть. Мои друзья смотрят очень внимательно. Они не знают, как это делается. Я маленький волшебник.',
    'Wir machen heute einen langen Spaziergang. Wir entdecken viele neue Wege. Wir finden einen versteckten Spielplatz. Die Bewegung an der Luft tut gut. Wir sind danach angenehm müde.': 'Мы сегодня совершаем долгую прогулку. Мы открываем много новых тропинок. Мы находим спрятанную игровую площадку. Движение на воздухе идет на пользу. После этого мы чувствуем приятную усталость.',
    'Ich male ein Bild für meine Oma. Ich benutze viele glitzernde Farben. Es zeigt einen Engel im Himmel. Oma wird sich sicher sehr freuen. Geschenke machen glücklich.': 'Я рисую картинку для своей бабушки. Я использую много блестящих красок. На ней изображен ангел в небе. Бабушка наверняка очень обрадуется. Подарки делают людей счастливыми.',
    'Wir spielen heute Verstecken im Haus. Ich finde ein sehr gutes Versteck. Mein Bruder sucht mich überall. Er läuft direkt an mir vorbei. Ich muss ganz leise kichern.': 'Мы сегодня играем в прятки в доме. Я нахожу очень хорошее укрытие. Мой брат ищет меня повсюду. Он проходит прямо мимо меня. Мне приходится тихонько хихикать.',
    'Ich lese ein Comic über Superhelden. Der Held kann fliegen und ist stark. Er hilft Menschen in großer Gefahr. Die Bilder sind sehr spannend gemalt. Ich lese den Comic mehrmals.': 'Я читаю комикс о супергероях. Герой умеет летать и он сильный. Он помогает людям в большой опасности. Картинки нарисованы очень захватывающе. Я перечитываю комикс несколько раз.',
    'Wir bauen eine Höhle aus Decken. Wir nehmen Kissen und eine Taschenlampe. Drinnen ist es dunkel und gemütlich. Wir erzählen uns dort Geheimnisse. Unsere Höhle ist der beste Ort.': 'Мы строим пещеру из одеял. Мы берем подушки и фонарик. Внутри темно и уютно. Мы рассказываем там друг другу секреты. Наша пещера — лучшее место.',
    'Ich helfe beim Kochen in der Küche. Ich schneide die weichen Gurken. Ich wasche den grünen Salat ab. Wir bereiten ein gesundes Essen vor. Kochen ist eine tolle Aufgabe.': 'Я помогаю готовить на кухне. Я режу мягкие огурцы. Я мою зеленый салат. Мы готовим здоровую еду. Готовить — это отличное задание.',
    'Wir tanzen zur Musik im Wohnzimmer. Wir drehen uns schnell im Kreis. Wir machen lustige Bewegungen dazu. Das Tanzen macht uns richtig fröhlich. Wir haben viel Energie.': 'Мы танцуем под музыку в гостиной. Мы быстро кружимся. Мы делаем при этом смешные движения. Танец делает нас по-настоящему веселыми. У нас много энергии.',
    'Ich schaue mir die Wolken am Himmel an. Eine Wolke sieht aus wie ein Hund. Eine andere sieht aus wie ein Baum. Der Wind schiebt die Wolken weiter. Träumen unter blauem Himmel.': 'Я рассматриваю облака на небе. Одно облако похоже на собаку. Другое похоже на дерево. Ветер гонит облака дальше. Мечты под синим небом.',
    'Heute war ein wirklich toller Tag. Ich habe viel gelernt und gelacht. Ich freue mich auf den nächsten Tag. Ich kuschele mich in mein Bett. Schlaf gut und träum süß.': 'Сегодня был действительно отличный день. Я многому научился и много смеялся. Я с нетерпением жду завтрашнего дня. Я уютно устраиваюсь в своей постели. Спи крепко и сладких снов.'
};

const fs = require('fs');
const path = 'c:/Users/Cubic/Downloads/Math-kids.buld.new/web-app/src/utils/translationData.ts';
let content = fs.readFileSync(path, 'utf8');

// Find the place where the translations object ends.
// It ends at line 537 in the last view_file, which was "};"
// But it's better to find it dynamically.

const lines = content.split('\n');
let closingBraceLine = -1;
for (let i = lines.length - 1; i >= 0; i--) {
    if (lines[i].trim() === '};') {
        closingBraceLine = i;
        break;
    }
}

if (closingBraceLine !== -1) {
    const newLines = [];
    for (let i = 0; i < closingBraceLine; i++) {
        newLines.push(lines[i]);
    }
    
    newLines.push('    // Lola Level 4 Stories (100)');
    for (const [key, value] of Object.entries(translationsLvl4)) {
        newLines.push(`    '${key.replace(/'/g, "\\'")}': '${value.replace(/'/g, "\\'")}',`);
    }
    
    for (let i = closingBraceLine; i < lines.length; i++) {
        newLines.push(lines[i]);
    }
    
    fs.writeFileSync(path, newLines.join('\n'), 'utf8');
    console.log('Successfully added 100 Lola Level 4 translations.');
} else {
    console.log('Could not find closing brace for translations object.');
}
